In [2]:
import numpy as np

In [3]:
 import pandas as pd

In [4]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [5]:
s

a   -1.807781
b   -0.563224
c   -1.153319
d   -0.435958
e   -0.520499
dtype: float64

In [6]:
import matplotlib.pyplot as plt

In [7]:
diaper = pd.read_csv('data/diaper_data.csv')

In [8]:
diaper

    name              date status          note
0     心心  2016/11/13 17:00     嘘嘘           NaN
1     心心  2016/11/13 19:48  嘘嘘+便便           NaN
2     心心  2016/11/13 22:23     便便           NaN
3     心心  2016/11/14 00:19     便便  一点点，感觉很稀，穿厚点
4     心心  2016/11/14 04:33     嘘嘘           NaN
5     心心  2016/11/14 09:20     便便           NaN
6     心心  2016/11/14 11:33     便便           NaN
7     心心  2016/11/14 16:14     便便           NaN
8     心心  2016/11/14 21:12  嘘嘘+便便           NaN
9     心心  2016/11/14 23:12  嘘嘘+便便           NaN
10    心心  2016/11/15 00:32  嘘嘘+便便           有点稀
11    心心  2016/11/15 03:45     干爽           NaN
12    心心  2016/11/15 07:06     嘘嘘           NaN
13    心心  2016/11/15 10:30  嘘嘘+便便           NaN
14    心心  2016/11/15 10:39     便便           NaN
15    心心  2016/11/15 11:40  嘘嘘+便便           NaN
16    心心  2016/11/15 16:28     便便      有的稀，颜色金黄
17    心心  2016/11/15 19:39  嘘嘘+便便           NaN
18    心心  2016/11/15 23:11     便便           NaN
19    心心  2016/11/16 02:25  嘘嘘+便便   主要是小便，大便一点点
20    心心  2016/11/16 05:33     嘘嘘           NaN
21    心心  2016/11/16 08:15  嘘嘘+便便          小便较多
22    心心  2016/11/16 12:09  嘘嘘+便便           NaN
23    心心  2016/11/16 14:21     嘘嘘           NaN
24    心心  2016/11/16 15:47  嘘嘘+便便         一点点大便
25    心心  2016/11/16 18:46  嘘嘘+便便     换的时候又尿了一泡
26    心心  2016/11/16 18:46     嘘嘘           NaN
27    心心  2016/11/16 19:53     便便           NaN
28    心心  2016/11/16 20:23  嘘嘘+便便           NaN
29    心心  2016/11/16 21:53     便便           NaN
..   ...               ...    ...           ...
609   心心  2017/02/13 06:03     嘘嘘           NaN
610   心心  2017/02/13 08:05     嘘嘘           NaN
611   心心  2017/02/13 12:40     嘘嘘           NaN
612   心心  2017/02/13 04:47     嘘嘘           NaN
613   心心  2017/02/13 10:00     嘘嘘           NaN
614   心心  2017/02/14 06:39     嘘嘘           NaN
615   心心  2017/02/14 08:34     嘘嘘           NaN
616   心心  2017/02/14 11:57     嘘嘘           NaN
617   心心  2017/02/14 04:13     嘘嘘           NaN
618   心心  2017/02/14 07:02     嘘嘘           NaN
619   心心  2017/02/14 09:10     嘘嘘           NaN
620   心心  2017/02/15 03:42     嘘嘘           NaN
621   心心  2017/02/15 08:00     嘘嘘           NaN
622   心心  2017/02/15 12:01     嘘嘘           NaN
623   心心  2017/02/15 04:06     嘘嘘           NaN
624   心心  2017/02/15 05:42     嘘嘘           NaN
625   心心  2017/02/15 10:43     嘘嘘           NaN
626   心心  2017/02/16 06:12     嘘嘘           NaN
627   心心  2017/02/16 10:28     嘘嘘           NaN
628   心心  2017/02/16 12:52     嘘嘘           NaN
629   心心  2017/02/16 05:39     嘘嘘           NaN
630   心心  2017/02/16 08:18     嘘嘘           NaN
631   心心  2017/02/17 06:49     嘘嘘           NaN
632   心心  2017/02/17 07:13     便便           NaN
633   心心  2017/02/17 10:31     嘘嘘           NaN
634   心心  2017/02/17 02:00     嘘嘘           NaN
635   心心  2017/02/17 06:23     嘘嘘           NaN
636   心心  2017/02/18 12:49     嘘嘘           NaN
637   心心  2017/02/18 08:33     嘘嘘           NaN
638   心心  2017/02/18 03:44     嘘嘘           NaN

[639 rows x 4 columns]

In [11]:
pd.TimeGrouper("M")

In [13]:
diaper['date'] = pd.to_datetime(diaper['date'],format='%Y/%m/%d %H:%M')

In [14]:
diaper

    name                date status          note
0     心心 2016-11-13 17:00:00     嘘嘘           NaN
1     心心 2016-11-13 19:48:00  嘘嘘+便便           NaN
2     心心 2016-11-13 22:23:00     便便           NaN
3     心心 2016-11-14 00:19:00     便便  一点点，感觉很稀，穿厚点
4     心心 2016-11-14 04:33:00     嘘嘘           NaN
5     心心 2016-11-14 09:20:00     便便           NaN
6     心心 2016-11-14 11:33:00     便便           NaN
7     心心 2016-11-14 16:14:00     便便           NaN
8     心心 2016-11-14 21:12:00  嘘嘘+便便           NaN
9     心心 2016-11-14 23:12:00  嘘嘘+便便           NaN
10    心心 2016-11-15 00:32:00  嘘嘘+便便           有点稀
11    心心 2016-11-15 03:45:00     干爽           NaN
12    心心 2016-11-15 07:06:00     嘘嘘           NaN
13    心心 2016-11-15 10:30:00  嘘嘘+便便           NaN
14    心心 2016-11-15 10:39:00     便便           NaN
15    心心 2016-11-15 11:40:00  嘘嘘+便便           NaN
16    心心 2016-11-15 16:28:00     便便      有的稀，颜色金黄
17    心心 2016-11-15 19:39:00  嘘嘘+便便           NaN
18    心心 2016-11-15 23:11:00     便便           NaN
19    心心 2016-11-16 02:25:00  嘘嘘+便便   主要是小便，大便一点点
20    心心 2016-11-16 05:33:00     嘘嘘           NaN
21    心心 2016-11-16 08:15:00  嘘嘘+便便          小便较多
22    心心 2016-11-16 12:09:00  嘘嘘+便便           NaN
23    心心 2016-11-16 14:21:00     嘘嘘           NaN
24    心心 2016-11-16 15:47:00  嘘嘘+便便         一点点大便
25    心心 2016-11-16 18:46:00  嘘嘘+便便     换的时候又尿了一泡
26    心心 2016-11-16 18:46:00     嘘嘘           NaN
27    心心 2016-11-16 19:53:00     便便           NaN
28    心心 2016-11-16 20:23:00  嘘嘘+便便           NaN
29    心心 2016-11-16 21:53:00     便便           NaN
..   ...                 ...    ...           ...
609   心心 2017-02-13 06:03:00     嘘嘘           NaN
610   心心 2017-02-13 08:05:00     嘘嘘           NaN
611   心心 2017-02-13 12:40:00     嘘嘘           NaN
612   心心 2017-02-13 04:47:00     嘘嘘           NaN
613   心心 2017-02-13 10:00:00     嘘嘘           NaN
614   心心 2017-02-14 06:39:00     嘘嘘           NaN
615   心心 2017-02-14 08:34:00     嘘嘘           NaN
616   心心 2017-02-14 11:57:00     嘘嘘           NaN
617   心心 2017-02-14 04:13:00     嘘嘘           NaN
618   心心 2017-02-14 07:02:00     嘘嘘           NaN
619   心心 2017-02-14 09:10:00     嘘嘘           NaN
620   心心 2017-02-15 03:42:00     嘘嘘           NaN
621   心心 2017-02-15 08:00:00     嘘嘘           NaN
622   心心 2017-02-15 12:01:00     嘘嘘           NaN
623   心心 2017-02-15 04:06:00     嘘嘘           NaN
624   心心 2017-02-15 05:42:00     嘘嘘           NaN
625   心心 2017-02-15 10:43:00     嘘嘘           NaN
626   心心 2017-02-16 06:12:00     嘘嘘           NaN
627   心心 2017-02-16 10:28:00     嘘嘘           NaN
628   心心 2017-02-16 12:52:00     嘘嘘           NaN
629   心心 2017-02-16 05:39:00     嘘嘘           NaN
630   心心 2017-02-16 08:18:00     嘘嘘           NaN
631   心心 2017-02-17 06:49:00     嘘嘘           NaN
632   心心 2017-02-17 07:13:00     便便           NaN
633   心心 2017-02-17 10:31:00     嘘嘘           NaN
634   心心 2017-02-17 02:00:00     嘘嘘           NaN
635   心心 2017-02-17 06:23:00     嘘嘘           NaN
636   心心 2017-02-18 12:49:00     嘘嘘           NaN
637   心心 2017-02-18 08:33:00     嘘嘘           NaN
638   心心 2017-02-18 03:44:00     嘘嘘           NaN

[639 rows x 4 columns]

In [17]:
diaper.groupby(by=diaper['date'], pd.TimeGrouper(freq='M'))

SyntaxError: non-keyword arg after keyword arg (<ipython-input-17-51a6bdd0881f>, line 1)

In [18]:
pd.DatetimeIndex(diaper['date']).normalize()

DatetimeIndex(['2016-11-13', '2016-11-13', '2016-11-13', '2016-11-14',
               '2016-11-14', '2016-11-14', '2016-11-14', '2016-11-14',
               '2016-11-14', '2016-11-14',
               ...
               '2017-02-16', '2017-02-16', '2017-02-17', '2017-02-17',
               '2017-02-17', '2017-02-17', '2017-02-17', '2017-02-18',
               '2017-02-18', '2017-02-18'],
              dtype='datetime64[ns]', name=u'date', length=639, freq=None)

In [19]:
g = df.groupby(pd.DatetimeIndex(diaper['date']).normalize())

NameError: name 'df' is not defined

In [20]:
g = diaper.groupby(pd.DatetimeIndex(diaper['date']).normalize())

In [21]:
g

In [22]:
g.count()

            name  date  status  note
date
2016-11-13     3     3       3     0
2016-11-14     7     7       7     1
2016-11-15     9     9       9     2
2016-11-16    12    12      12     4
2016-11-17     8     8       8     2
2016-11-18    10    10      10     1
2016-11-19     9     9       9     1
2016-11-20     8     8       8     3
2016-11-21    10    10      10     1
2016-11-22     7     7       7     1
2016-11-23    11    11      11     0
2016-11-24    10    10      10     0
2016-11-25     9     9       9     1
2016-11-26     9     9       9     1
2016-11-27     5     5       5     2
2016-11-28     9     9       9     1
2016-11-29     9     9       9     0
2016-11-30     7     7       7     0
2016-12-01     5     5       5     0
2016-12-02     7     7       7     0
2016-12-03     6     6       6     0
2016-12-04     7     7       7     1
2016-12-05     6     6       6     0
2016-12-06     8     8       8     0
2016-12-07     6     6       6     0
2016-12-08     6     6       6     0
2016-12-09     6     6       6     0
2016-12-10     7     7       7     1
2016-12-11     7     7       7     0
2016-12-12     7     7       7     0
...          ...   ...     ...   ...
2017-01-20     5     5       5     0
2017-01-21     7     7       7     0
2017-01-22     7     7       7     0
2017-01-23     6     6       6     0
2017-01-24     5     5       5     0
2017-01-25     7     7       7     0
2017-01-26     8     8       8     0
2017-01-27     6     6       6     0
2017-01-28     6     6       6     1
2017-01-29     6     6       6     0
2017-01-30     5     5       5     0
2017-01-31     4     4       4     1
2017-02-01     6     6       6     0
2017-02-02     5     5       5     0
2017-02-03     7     7       7     0
2017-02-04     4     4       4     0
2017-02-05     4     4       4     0
2017-02-06     4     4       4     0
2017-02-07     6     6       6     2
2017-02-08     7     7       7     1
2017-02-09     6     6       6     0
2017-02-10     5     5       5     2
2017-02-11     6     6       6     0
2017-02-12     7     7       7     1
2017-02-13     5     5       5     0
2017-02-14     6     6       6     0
2017-02-15     6     6       6     0
2017-02-16     5     5       5     0
2017-02-17     5     5       5     0
2017-02-18     3     3       3     0

[98 rows x 4 columns]

In [23]:
diaper['l'], diaper['c'] = diaper['status'].str.split('+', 1).str

In [24]:
diaper

    name                date status          note   l    c
0     心心 2016-11-13 17:00:00     嘘嘘           NaN  嘘嘘  NaN
1     心心 2016-11-13 19:48:00  嘘嘘+便便           NaN  嘘嘘   便便
2     心心 2016-11-13 22:23:00     便便           NaN  便便  NaN
3     心心 2016-11-14 00:19:00     便便  一点点，感觉很稀，穿厚点  便便  NaN
4     心心 2016-11-14 04:33:00     嘘嘘           NaN  嘘嘘  NaN
5     心心 2016-11-14 09:20:00     便便           NaN  便便  NaN
6     心心 2016-11-14 11:33:00     便便           NaN  便便  NaN
7     心心 2016-11-14 16:14:00     便便           NaN  便便  NaN
8     心心 2016-11-14 21:12:00  嘘嘘+便便           NaN  嘘嘘   便便
9     心心 2016-11-14 23:12:00  嘘嘘+便便           NaN  嘘嘘   便便
10    心心 2016-11-15 00:32:00  嘘嘘+便便           有点稀  嘘嘘   便便
11    心心 2016-11-15 03:45:00     干爽           NaN  干爽  NaN
12    心心 2016-11-15 07:06:00     嘘嘘           NaN  嘘嘘  NaN
13    心心 2016-11-15 10:30:00  嘘嘘+便便           NaN  嘘嘘   便便
14    心心 2016-11-15 10:39:00     便便           NaN  便便  NaN
15    心心 2016-11-15 11:40:00  嘘嘘+便便           NaN  嘘嘘   便便
16    心心 2016-11-15 16:28:00     便便      有的稀，颜色金黄  便便  NaN
17    心心 2016-11-15 19:39:00  嘘嘘+便便           NaN  嘘嘘   便便
18    心心 2016-11-15 23:11:00     便便           NaN  便便  NaN
19    心心 2016-11-16 02:25:00  嘘嘘+便便   主要是小便，大便一点点  嘘嘘   便便
20    心心 2016-11-16 05:33:00     嘘嘘           NaN  嘘嘘  NaN
21    心心 2016-11-16 08:15:00  嘘嘘+便便          小便较多  嘘嘘   便便
22    心心 2016-11-16 12:09:00  嘘嘘+便便           NaN  嘘嘘   便便
23    心心 2016-11-16 14:21:00     嘘嘘           NaN  嘘嘘  NaN
24    心心 2016-11-16 15:47:00  嘘嘘+便便         一点点大便  嘘嘘   便便
25    心心 2016-11-16 18:46:00  嘘嘘+便便     换的时候又尿了一泡  嘘嘘   便便
26    心心 2016-11-16 18:46:00     嘘嘘           NaN  嘘嘘  NaN
27    心心 2016-11-16 19:53:00     便便           NaN  便便  NaN
28    心心 2016-11-16 20:23:00  嘘嘘+便便           NaN  嘘嘘   便便
29    心心 2016-11-16 21:53:00     便便           NaN  便便  NaN
..   ...                 ...    ...           ...  ..  ...
609   心心 2017-02-13 06:03:00     嘘嘘           NaN  嘘嘘  NaN
610   心心 2017-02-13 08:05:00     嘘嘘           NaN  嘘嘘  NaN
611   心心 2017-02-13 12:40:00     嘘嘘           NaN  嘘嘘  NaN
612   心心 2017-02-13 04:47:00     嘘嘘           NaN  嘘嘘  NaN
613   心心 2017-02-13 10:00:00     嘘嘘           NaN  嘘嘘  NaN
614   心心 2017-02-14 06:39:00     嘘嘘           NaN  嘘嘘  NaN
615   心心 2017-02-14 08:34:00     嘘嘘           NaN  嘘嘘  NaN
616   心心 2017-02-14 11:57:00     嘘嘘           NaN  嘘嘘  NaN
617   心心 2017-02-14 04:13:00     嘘嘘           NaN  嘘嘘  NaN
618   心心 2017-02-14 07:02:00     嘘嘘           NaN  嘘嘘  NaN
619   心心 2017-02-14 09:10:00     嘘嘘           NaN  嘘嘘  NaN
620   心心 2017-02-15 03:42:00     嘘嘘           NaN  嘘嘘  NaN
621   心心 2017-02-15 08:00:00     嘘嘘           NaN  嘘嘘  NaN
622   心心 2017-02-15 12:01:00     嘘嘘           NaN  嘘嘘  NaN
623   心心 2017-02-15 04:06:00     嘘嘘           NaN  嘘嘘  NaN
624   心心 2017-02-15 05:42:00     嘘嘘           NaN  嘘嘘  NaN
625   心心 2017-02-15 10:43:00     嘘嘘           NaN  嘘嘘  NaN
626   心心 2017-02-16 06:12:00     嘘嘘           NaN  嘘嘘  NaN
627   心心 2017-02-16 10:28:00     嘘嘘           NaN  嘘嘘  NaN
628   心心 2017-02-16 12:52:00     嘘嘘           NaN  嘘嘘  NaN
629   心心 2017-02-16 05:39:00     嘘嘘           NaN  嘘嘘  NaN
630   心心 2017-02-16 08:18:00     嘘嘘           NaN  嘘嘘  NaN
631   心心 2017-02-17 06:49:00     嘘嘘           NaN  嘘嘘  NaN
632   心心 2017-02-17 07:13:00     便便           NaN  便便  NaN
633   心心 2017-02-17 10:31:00     嘘嘘           NaN  嘘嘘  NaN
634   心心 2017-02-17 02:00:00     嘘嘘           NaN  嘘嘘  NaN
635   心心 2017-02-17 06:23:00     嘘嘘           NaN  嘘嘘  NaN
636   心心 2017-02-18 12:49:00     嘘嘘           NaN  嘘嘘  NaN
637   心心 2017-02-18 08:33:00     嘘嘘           NaN  嘘嘘  NaN
638   心心 2017-02-18 03:44:00     嘘嘘           NaN  嘘嘘  NaN

[639 rows x 6 columns]

In [25]:
df = pd.DataFrame(diaper)

In [26]:
df

    name                date status          note   l    c
0     心心 2016-11-13 17:00:00     嘘嘘           NaN  嘘嘘  NaN
1     心心 2016-11-13 19:48:00  嘘嘘+便便           NaN  嘘嘘   便便
2     心心 2016-11-13 22:23:00     便便           NaN  便便  NaN
3     心心 2016-11-14 00:19:00     便便  一点点，感觉很稀，穿厚点  便便  NaN
4     心心 2016-11-14 04:33:00     嘘嘘           NaN  嘘嘘  NaN
5     心心 2016-11-14 09:20:00     便便           NaN  便便  NaN
6     心心 2016-11-14 11:33:00     便便           NaN  便便  NaN
7     心心 2016-11-14 16:14:00     便便           NaN  便便  NaN
8     心心 2016-11-14 21:12:00  嘘嘘+便便           NaN  嘘嘘   便便
9     心心 2016-11-14 23:12:00  嘘嘘+便便           NaN  嘘嘘   便便
10    心心 2016-11-15 00:32:00  嘘嘘+便便           有点稀  嘘嘘   便便
11    心心 2016-11-15 03:45:00     干爽           NaN  干爽  NaN
12    心心 2016-11-15 07:06:00     嘘嘘           NaN  嘘嘘  NaN
13    心心 2016-11-15 10:30:00  嘘嘘+便便           NaN  嘘嘘   便便
14    心心 2016-11-15 10:39:00     便便           NaN  便便  NaN
15    心心 2016-11-15 11:40:00  嘘嘘+便便           NaN  嘘嘘   便便
16    心心 2016-11-15 16:28:00     便便      有的稀，颜色金黄  便便  NaN
17    心心 2016-11-15 19:39:00  嘘嘘+便便           NaN  嘘嘘   便便
18    心心 2016-11-15 23:11:00     便便           NaN  便便  NaN
19    心心 2016-11-16 02:25:00  嘘嘘+便便   主要是小便，大便一点点  嘘嘘   便便
20    心心 2016-11-16 05:33:00     嘘嘘           NaN  嘘嘘  NaN
21    心心 2016-11-16 08:15:00  嘘嘘+便便          小便较多  嘘嘘   便便
22    心心 2016-11-16 12:09:00  嘘嘘+便便           NaN  嘘嘘   便便
23    心心 2016-11-16 14:21:00     嘘嘘           NaN  嘘嘘  NaN
24    心心 2016-11-16 15:47:00  嘘嘘+便便         一点点大便  嘘嘘   便便
25    心心 2016-11-16 18:46:00  嘘嘘+便便     换的时候又尿了一泡  嘘嘘   便便
26    心心 2016-11-16 18:46:00     嘘嘘           NaN  嘘嘘  NaN
27    心心 2016-11-16 19:53:00     便便           NaN  便便  NaN
28    心心 2016-11-16 20:23:00  嘘嘘+便便           NaN  嘘嘘   便便
29    心心 2016-11-16 21:53:00     便便           NaN  便便  NaN
..   ...                 ...    ...           ...  ..  ...
609   心心 2017-02-13 06:03:00     嘘嘘           NaN  嘘嘘  NaN
610   心心 2017-02-13 08:05:00     嘘嘘           NaN  嘘嘘  NaN
611   心心 2017-02-13 12:40:00     嘘嘘           NaN  嘘嘘  NaN
612   心心 2017-02-13 04:47:00     嘘嘘           NaN  嘘嘘  NaN
613   心心 2017-02-13 10:00:00     嘘嘘           NaN  嘘嘘  NaN
614   心心 2017-02-14 06:39:00     嘘嘘           NaN  嘘嘘  NaN
615   心心 2017-02-14 08:34:00     嘘嘘           NaN  嘘嘘  NaN
616   心心 2017-02-14 11:57:00     嘘嘘           NaN  嘘嘘  NaN
617   心心 2017-02-14 04:13:00     嘘嘘           NaN  嘘嘘  NaN
618   心心 2017-02-14 07:02:00     嘘嘘           NaN  嘘嘘  NaN
619   心心 2017-02-14 09:10:00     嘘嘘           NaN  嘘嘘  NaN
620   心心 2017-02-15 03:42:00     嘘嘘           NaN  嘘嘘  NaN
621   心心 2017-02-15 08:00:00     嘘嘘           NaN  嘘嘘  NaN
622   心心 2017-02-15 12:01:00     嘘嘘           NaN  嘘嘘  NaN
623   心心 2017-02-15 04:06:00     嘘嘘           NaN  嘘嘘  NaN
624   心心 2017-02-15 05:42:00     嘘嘘           NaN  嘘嘘  NaN
625   心心 2017-02-15 10:43:00     嘘嘘           NaN  嘘嘘  NaN
626   心心 2017-02-16 06:12:00     嘘嘘           NaN  嘘嘘  NaN
627   心心 2017-02-16 10:28:00     嘘嘘           NaN  嘘嘘  NaN
628   心心 2017-02-16 12:52:00     嘘嘘           NaN  嘘嘘  NaN
629   心心 2017-02-16 05:39:00     嘘嘘           NaN  嘘嘘  NaN
630   心心 2017-02-16 08:18:00     嘘嘘           NaN  嘘嘘  NaN
631   心心 2017-02-17 06:49:00     嘘嘘           NaN  嘘嘘  NaN
632   心心 2017-02-17 07:13:00     便便           NaN  便便  NaN
633   心心 2017-02-17 10:31:00     嘘嘘           NaN  嘘嘘  NaN
634   心心 2017-02-17 02:00:00     嘘嘘           NaN  嘘嘘  NaN
635   心心 2017-02-17 06:23:00     嘘嘘           NaN  嘘嘘  NaN
636   心心 2017-02-18 12:49:00     嘘嘘           NaN  嘘嘘  NaN
637   心心 2017-02-18 08:33:00     嘘嘘           NaN  嘘嘘  NaN
638   心心 2017-02-18 03:44:00     嘘嘘           NaN  嘘嘘  NaN

[639 rows x 6 columns]

In [30]:
df['status'] = df['status'].str.split('+', 1)

In [34]:
df['L'], df['C'] = df['status']

ValueError: too many values to unpack

In [35]:
diaper = pd.read_csv('data/diaper_data.csv')

In [36]:
diaper['l'], diaper['c'] = diaper['status'].str.split('+', 1).str

In [37]:
diaper

    name              date status          note   l    c
0     心心  2016/11/13 17:00     嘘嘘           NaN  嘘嘘  NaN
1     心心  2016/11/13 19:48  嘘嘘+便便           NaN  嘘嘘   便便
2     心心  2016/11/13 22:23     便便           NaN  便便  NaN
3     心心  2016/11/14 00:19     便便  一点点，感觉很稀，穿厚点  便便  NaN
4     心心  2016/11/14 04:33     嘘嘘           NaN  嘘嘘  NaN
5     心心  2016/11/14 09:20     便便           NaN  便便  NaN
6     心心  2016/11/14 11:33     便便           NaN  便便  NaN
7     心心  2016/11/14 16:14     便便           NaN  便便  NaN
8     心心  2016/11/14 21:12  嘘嘘+便便           NaN  嘘嘘   便便
9     心心  2016/11/14 23:12  嘘嘘+便便           NaN  嘘嘘   便便
10    心心  2016/11/15 00:32  嘘嘘+便便           有点稀  嘘嘘   便便
11    心心  2016/11/15 03:45     干爽           NaN  干爽  NaN
12    心心  2016/11/15 07:06     嘘嘘           NaN  嘘嘘  NaN
13    心心  2016/11/15 10:30  嘘嘘+便便           NaN  嘘嘘   便便
14    心心  2016/11/15 10:39     便便           NaN  便便  NaN
15    心心  2016/11/15 11:40  嘘嘘+便便           NaN  嘘嘘   便便
16    心心  2016/11/15 16:28     便便      有的稀，颜色金黄  便便  NaN
17    心心  2016/11/15 19:39  嘘嘘+便便           NaN  嘘嘘   便便
18    心心  2016/11/15 23:11     便便           NaN  便便  NaN
19    心心  2016/11/16 02:25  嘘嘘+便便   主要是小便，大便一点点  嘘嘘   便便
20    心心  2016/11/16 05:33     嘘嘘           NaN  嘘嘘  NaN
21    心心  2016/11/16 08:15  嘘嘘+便便          小便较多  嘘嘘   便便
22    心心  2016/11/16 12:09  嘘嘘+便便           NaN  嘘嘘   便便
23    心心  2016/11/16 14:21     嘘嘘           NaN  嘘嘘  NaN
24    心心  2016/11/16 15:47  嘘嘘+便便         一点点大便  嘘嘘   便便
25    心心  2016/11/16 18:46  嘘嘘+便便     换的时候又尿了一泡  嘘嘘   便便
26    心心  2016/11/16 18:46     嘘嘘           NaN  嘘嘘  NaN
27    心心  2016/11/16 19:53     便便           NaN  便便  NaN
28    心心  2016/11/16 20:23  嘘嘘+便便           NaN  嘘嘘   便便
29    心心  2016/11/16 21:53     便便           NaN  便便  NaN
..   ...               ...    ...           ...  ..  ...
609   心心  2017/02/13 06:03     嘘嘘           NaN  嘘嘘  NaN
610   心心  2017/02/13 08:05     嘘嘘           NaN  嘘嘘  NaN
611   心心  2017/02/13 12:40     嘘嘘           NaN  嘘嘘  NaN
612   心心  2017/02/13 04:47     嘘嘘           NaN  嘘嘘  NaN
613   心心  2017/02/13 10:00     嘘嘘           NaN  嘘嘘  NaN
614   心心  2017/02/14 06:39     嘘嘘           NaN  嘘嘘  NaN
615   心心  2017/02/14 08:34     嘘嘘           NaN  嘘嘘  NaN
616   心心  2017/02/14 11:57     嘘嘘           NaN  嘘嘘  NaN
617   心心  2017/02/14 04:13     嘘嘘           NaN  嘘嘘  NaN
618   心心  2017/02/14 07:02     嘘嘘           NaN  嘘嘘  NaN
619   心心  2017/02/14 09:10     嘘嘘           NaN  嘘嘘  NaN
620   心心  2017/02/15 03:42     嘘嘘           NaN  嘘嘘  NaN
621   心心  2017/02/15 08:00     嘘嘘           NaN  嘘嘘  NaN
622   心心  2017/02/15 12:01     嘘嘘           NaN  嘘嘘  NaN
623   心心  2017/02/15 04:06     嘘嘘           NaN  嘘嘘  NaN
624   心心  2017/02/15 05:42     嘘嘘           NaN  嘘嘘  NaN
625   心心  2017/02/15 10:43     嘘嘘           NaN  嘘嘘  NaN
626   心心  2017/02/16 06:12     嘘嘘           NaN  嘘嘘  NaN
627   心心  2017/02/16 10:28     嘘嘘           NaN  嘘嘘  NaN
628   心心  2017/02/16 12:52     嘘嘘           NaN  嘘嘘  NaN
629   心心  2017/02/16 05:39     嘘嘘           NaN  嘘嘘  NaN
630   心心  2017/02/16 08:18     嘘嘘           NaN  嘘嘘  NaN
631   心心  2017/02/17 06:49     嘘嘘           NaN  嘘嘘  NaN
632   心心  2017/02/17 07:13     便便           NaN  便便  NaN
633   心心  2017/02/17 10:31     嘘嘘           NaN  嘘嘘  NaN
634   心心  2017/02/17 02:00     嘘嘘           NaN  嘘嘘  NaN
635   心心  2017/02/17 06:23     嘘嘘           NaN  嘘嘘  NaN
636   心心  2017/02/18 12:49     嘘嘘           NaN  嘘嘘  NaN
637   心心  2017/02/18 08:33     嘘嘘           NaN  嘘嘘  NaN
638   心心  2017/02/18 03:44     嘘嘘           NaN  嘘嘘  NaN

[639 rows x 6 columns]

In [39]:
diaper.fillna({'l': '0', 'c': '0'})

    name              date status          note   l   c
0     心心  2016/11/13 17:00     嘘嘘           NaN  嘘嘘   0
1     心心  2016/11/13 19:48  嘘嘘+便便           NaN  嘘嘘  便便
2     心心  2016/11/13 22:23     便便           NaN  便便   0
3     心心  2016/11/14 00:19     便便  一点点，感觉很稀，穿厚点  便便   0
4     心心  2016/11/14 04:33     嘘嘘           NaN  嘘嘘   0
5     心心  2016/11/14 09:20     便便           NaN  便便   0
6     心心  2016/11/14 11:33     便便           NaN  便便   0
7     心心  2016/11/14 16:14     便便           NaN  便便   0
8     心心  2016/11/14 21:12  嘘嘘+便便           NaN  嘘嘘  便便
9     心心  2016/11/14 23:12  嘘嘘+便便           NaN  嘘嘘  便便
10    心心  2016/11/15 00:32  嘘嘘+便便           有点稀  嘘嘘  便便
11    心心  2016/11/15 03:45     干爽           NaN  干爽   0
12    心心  2016/11/15 07:06     嘘嘘           NaN  嘘嘘   0
13    心心  2016/11/15 10:30  嘘嘘+便便           NaN  嘘嘘  便便
14    心心  2016/11/15 10:39     便便           NaN  便便   0
15    心心  2016/11/15 11:40  嘘嘘+便便           NaN  嘘嘘  便便
16    心心  2016/11/15 16:28     便便      有的稀，颜色金黄  便便   0
17    心心  2016/11/15 19:39  嘘嘘+便便           NaN  嘘嘘  便便
18    心心  2016/11/15 23:11     便便           NaN  便便   0
19    心心  2016/11/16 02:25  嘘嘘+便便   主要是小便，大便一点点  嘘嘘  便便
20    心心  2016/11/16 05:33     嘘嘘           NaN  嘘嘘   0
21    心心  2016/11/16 08:15  嘘嘘+便便          小便较多  嘘嘘  便便
22    心心  2016/11/16 12:09  嘘嘘+便便           NaN  嘘嘘  便便
23    心心  2016/11/16 14:21     嘘嘘           NaN  嘘嘘   0
24    心心  2016/11/16 15:47  嘘嘘+便便         一点点大便  嘘嘘  便便
25    心心  2016/11/16 18:46  嘘嘘+便便     换的时候又尿了一泡  嘘嘘  便便
26    心心  2016/11/16 18:46     嘘嘘           NaN  嘘嘘   0
27    心心  2016/11/16 19:53     便便           NaN  便便   0
28    心心  2016/11/16 20:23  嘘嘘+便便           NaN  嘘嘘  便便
29    心心  2016/11/16 21:53     便便           NaN  便便   0
..   ...               ...    ...           ...  ..  ..
609   心心  2017/02/13 06:03     嘘嘘           NaN  嘘嘘   0
610   心心  2017/02/13 08:05     嘘嘘           NaN  嘘嘘   0
611   心心  2017/02/13 12:40     嘘嘘           NaN  嘘嘘   0
612   心心  2017/02/13 04:47     嘘嘘           NaN  嘘嘘   0
613   心心  2017/02/13 10:00     嘘嘘           NaN  嘘嘘   0
614   心心  2017/02/14 06:39     嘘嘘           NaN  嘘嘘   0
615   心心  2017/02/14 08:34     嘘嘘           NaN  嘘嘘   0
616   心心  2017/02/14 11:57     嘘嘘           NaN  嘘嘘   0
617   心心  2017/02/14 04:13     嘘嘘           NaN  嘘嘘   0
618   心心  2017/02/14 07:02     嘘嘘           NaN  嘘嘘   0
619   心心  2017/02/14 09:10     嘘嘘           NaN  嘘嘘   0
620   心心  2017/02/15 03:42     嘘嘘           NaN  嘘嘘   0
621   心心  2017/02/15 08:00     嘘嘘           NaN  嘘嘘   0
622   心心  2017/02/15 12:01     嘘嘘           NaN  嘘嘘   0
623   心心  2017/02/15 04:06     嘘嘘           NaN  嘘嘘   0
624   心心  2017/02/15 05:42     嘘嘘           NaN  嘘嘘   0
625   心心  2017/02/15 10:43     嘘嘘           NaN  嘘嘘   0
626   心心  2017/02/16 06:12     嘘嘘           NaN  嘘嘘   0
627   心心  2017/02/16 10:28     嘘嘘           NaN  嘘嘘   0
628   心心  2017/02/16 12:52     嘘嘘           NaN  嘘嘘   0
629   心心  2017/02/16 05:39     嘘嘘           NaN  嘘嘘   0
630   心心  2017/02/16 08:18     嘘嘘           NaN  嘘嘘   0
631   心心  2017/02/17 06:49     嘘嘘           NaN  嘘嘘   0
632   心心  2017/02/17 07:13     便便           NaN  便便   0
633   心心  2017/02/17 10:31     嘘嘘           NaN  嘘嘘   0
634   心心  2017/02/17 02:00     嘘嘘           NaN  嘘嘘   0
635   心心  2017/02/17 06:23     嘘嘘           NaN  嘘嘘   0
636   心心  2017/02/18 12:49     嘘嘘           NaN  嘘嘘   0
637   心心  2017/02/18 08:33     嘘嘘           NaN  嘘嘘   0
638   心心  2017/02/18 03:44     嘘嘘           NaN  嘘嘘   0

[639 rows x 6 columns]

In [40]:
del diaper['name']

In [41]:
del diaper['note']

In [42]:
diaper

                 date status   l    c
0    2016/11/13 17:00     嘘嘘  嘘嘘  NaN
1    2016/11/13 19:48  嘘嘘+便便  嘘嘘   便便
2    2016/11/13 22:23     便便  便便  NaN
3    2016/11/14 00:19     便便  便便  NaN
4    2016/11/14 04:33     嘘嘘  嘘嘘  NaN
5    2016/11/14 09:20     便便  便便  NaN
6    2016/11/14 11:33     便便  便便  NaN
7    2016/11/14 16:14     便便  便便  NaN
8    2016/11/14 21:12  嘘嘘+便便  嘘嘘   便便
9    2016/11/14 23:12  嘘嘘+便便  嘘嘘   便便
10   2016/11/15 00:32  嘘嘘+便便  嘘嘘   便便
11   2016/11/15 03:45     干爽  干爽  NaN
12   2016/11/15 07:06     嘘嘘  嘘嘘  NaN
13   2016/11/15 10:30  嘘嘘+便便  嘘嘘   便便
14   2016/11/15 10:39     便便  便便  NaN
15   2016/11/15 11:40  嘘嘘+便便  嘘嘘   便便
16   2016/11/15 16:28     便便  便便  NaN
17   2016/11/15 19:39  嘘嘘+便便  嘘嘘   便便
18   2016/11/15 23:11     便便  便便  NaN
19   2016/11/16 02:25  嘘嘘+便便  嘘嘘   便便
20   2016/11/16 05:33     嘘嘘  嘘嘘  NaN
21   2016/11/16 08:15  嘘嘘+便便  嘘嘘   便便
22   2016/11/16 12:09  嘘嘘+便便  嘘嘘   便便
23   2016/11/16 14:21     嘘嘘  嘘嘘  NaN
24   2016/11/16 15:47  嘘嘘+便便  嘘嘘   便便
25   2016/11/16 18:46  嘘嘘+便便  嘘嘘   便便
26   2016/11/16 18:46     嘘嘘  嘘嘘  NaN
27   2016/11/16 19:53     便便  便便  NaN
28   2016/11/16 20:23  嘘嘘+便便  嘘嘘   便便
29   2016/11/16 21:53     便便  便便  NaN
..                ...    ...  ..  ...
609  2017/02/13 06:03     嘘嘘  嘘嘘  NaN
610  2017/02/13 08:05     嘘嘘  嘘嘘  NaN
611  2017/02/13 12:40     嘘嘘  嘘嘘  NaN
612  2017/02/13 04:47     嘘嘘  嘘嘘  NaN
613  2017/02/13 10:00     嘘嘘  嘘嘘  NaN
614  2017/02/14 06:39     嘘嘘  嘘嘘  NaN
615  2017/02/14 08:34     嘘嘘  嘘嘘  NaN
616  2017/02/14 11:57     嘘嘘  嘘嘘  NaN
617  2017/02/14 04:13     嘘嘘  嘘嘘  NaN
618  2017/02/14 07:02     嘘嘘  嘘嘘  NaN
619  2017/02/14 09:10     嘘嘘  嘘嘘  NaN
620  2017/02/15 03:42     嘘嘘  嘘嘘  NaN
621  2017/02/15 08:00     嘘嘘  嘘嘘  NaN
622  2017/02/15 12:01     嘘嘘  嘘嘘  NaN
623  2017/02/15 04:06     嘘嘘  嘘嘘  NaN
624  2017/02/15 05:42     嘘嘘  嘘嘘  NaN
625  2017/02/15 10:43     嘘嘘  嘘嘘  NaN
626  2017/02/16 06:12     嘘嘘  嘘嘘  NaN
627  2017/02/16 10:28     嘘嘘  嘘嘘  NaN
628  2017/02/16 12:52     嘘嘘  嘘嘘  NaN
629  2017/02/16 05:39     嘘嘘  嘘嘘  NaN
630  2017/02/16 08:18     嘘嘘  嘘嘘  NaN
631  2017/02/17 06:49     嘘嘘  嘘嘘  NaN
632  2017/02/17 07:13     便便  便便  NaN
633  2017/02/17 10:31     嘘嘘  嘘嘘  NaN
634  2017/02/17 02:00     嘘嘘  嘘嘘  NaN
635  2017/02/17 06:23     嘘嘘  嘘嘘  NaN
636  2017/02/18 12:49     嘘嘘  嘘嘘  NaN
637  2017/02/18 08:33     嘘嘘  嘘嘘  NaN
638  2017/02/18 03:44     嘘嘘  嘘嘘  NaN

[639 rows x 4 columns]

In [43]:
diaper.fillna({'l': '0', 'c': '0'})

                 date status   l   c
0    2016/11/13 17:00     嘘嘘  嘘嘘   0
1    2016/11/13 19:48  嘘嘘+便便  嘘嘘  便便
2    2016/11/13 22:23     便便  便便   0
3    2016/11/14 00:19     便便  便便   0
4    2016/11/14 04:33     嘘嘘  嘘嘘   0
5    2016/11/14 09:20     便便  便便   0
6    2016/11/14 11:33     便便  便便   0
7    2016/11/14 16:14     便便  便便   0
8    2016/11/14 21:12  嘘嘘+便便  嘘嘘  便便
9    2016/11/14 23:12  嘘嘘+便便  嘘嘘  便便
10   2016/11/15 00:32  嘘嘘+便便  嘘嘘  便便
11   2016/11/15 03:45     干爽  干爽   0
12   2016/11/15 07:06     嘘嘘  嘘嘘   0
13   2016/11/15 10:30  嘘嘘+便便  嘘嘘  便便
14   2016/11/15 10:39     便便  便便   0
15   2016/11/15 11:40  嘘嘘+便便  嘘嘘  便便
16   2016/11/15 16:28     便便  便便   0
17   2016/11/15 19:39  嘘嘘+便便  嘘嘘  便便
18   2016/11/15 23:11     便便  便便   0
19   2016/11/16 02:25  嘘嘘+便便  嘘嘘  便便
20   2016/11/16 05:33     嘘嘘  嘘嘘   0
21   2016/11/16 08:15  嘘嘘+便便  嘘嘘  便便
22   2016/11/16 12:09  嘘嘘+便便  嘘嘘  便便
23   2016/11/16 14:21     嘘嘘  嘘嘘   0
24   2016/11/16 15:47  嘘嘘+便便  嘘嘘  便便
25   2016/11/16 18:46  嘘嘘+便便  嘘嘘  便便
26   2016/11/16 18:46     嘘嘘  嘘嘘   0
27   2016/11/16 19:53     便便  便便   0
28   2016/11/16 20:23  嘘嘘+便便  嘘嘘  便便
29   2016/11/16 21:53     便便  便便   0
..                ...    ...  ..  ..
609  2017/02/13 06:03     嘘嘘  嘘嘘   0
610  2017/02/13 08:05     嘘嘘  嘘嘘   0
611  2017/02/13 12:40     嘘嘘  嘘嘘   0
612  2017/02/13 04:47     嘘嘘  嘘嘘   0
613  2017/02/13 10:00     嘘嘘  嘘嘘   0
614  2017/02/14 06:39     嘘嘘  嘘嘘   0
615  2017/02/14 08:34     嘘嘘  嘘嘘   0
616  2017/02/14 11:57     嘘嘘  嘘嘘   0
617  2017/02/14 04:13     嘘嘘  嘘嘘   0
618  2017/02/14 07:02     嘘嘘  嘘嘘   0
619  2017/02/14 09:10     嘘嘘  嘘嘘   0
620  2017/02/15 03:42     嘘嘘  嘘嘘   0
621  2017/02/15 08:00     嘘嘘  嘘嘘   0
622  2017/02/15 12:01     嘘嘘  嘘嘘   0
623  2017/02/15 04:06     嘘嘘  嘘嘘   0
624  2017/02/15 05:42     嘘嘘  嘘嘘   0
625  2017/02/15 10:43     嘘嘘  嘘嘘   0
626  2017/02/16 06:12     嘘嘘  嘘嘘   0
627  2017/02/16 10:28     嘘嘘  嘘嘘   0
628  2017/02/16 12:52     嘘嘘  嘘嘘   0
629  2017/02/16 05:39     嘘嘘  嘘嘘   0
630  2017/02/16 08:18     嘘嘘  嘘嘘   0
631  2017/02/17 06:49     嘘嘘  嘘嘘   0
632  2017/02/17 07:13     便便  便便   0
633  2017/02/17 10:31     嘘嘘  嘘嘘   0
634  2017/02/17 02:00     嘘嘘  嘘嘘   0
635  2017/02/17 06:23     嘘嘘  嘘嘘   0
636  2017/02/18 12:49     嘘嘘  嘘嘘   0
637  2017/02/18 08:33     嘘嘘  嘘嘘   0
638  2017/02/18 03:44     嘘嘘  嘘嘘   0

[639 rows x 4 columns]

In [54]:
def mapper(key):
    if key == '嘘嘘':
        return pd.Series(['1', '0'], index=['l', 'c'])
    elif key == '便便':
        return pd.Series(['0', '1'], index=['l', 'c'])
    else:
        return pd.Series(['1', '1'], index=['l', 'c'])
    
x = diaper['status'].apply(mapper)

In [55]:
x

     0  1
0    1  0
1    1  1
2    0  1
3    0  1
4    1  0
5    0  1
6    0  1
7    0  1
8    1  1
9    1  1
10   1  1
11   1  1
12   1  0
13   1  1
14   0  1
15   1  1
16   0  1
17   1  1
18   0  1
19   1  1
20   1  0
21   1  1
22   1  1
23   1  0
24   1  1
25   1  1
26   1  0
27   0  1
28   1  1
29   0  1
..  .. ..
609  1  0
610  1  0
611  1  0
612  1  0
613  1  0
614  1  0
615  1  0
616  1  0
617  1  0
618  1  0
619  1  0
620  1  0
621  1  0
622  1  0
623  1  0
624  1  0
625  1  0
626  1  0
627  1  0
628  1  0
629  1  0
630  1  0
631  1  0
632  0  1
633  1  0
634  1  0
635  1  0
636  1  0
637  1  0
638  1  0

[639 rows x 2 columns]

In [62]:
diaper['status'].apply(mapper)

     0  1
0    1  0
1    1  1
2    0  1
3    0  1
4    1  0
5    0  1
6    0  1
7    0  1
8    1  1
9    1  1
10   1  1
11   1  1
12   1  0
13   1  1
14   0  1
15   1  1
16   0  1
17   1  1
18   0  1
19   1  1
20   1  0
21   1  1
22   1  1
23   1  0
24   1  1
25   1  1
26   1  0
27   0  1
28   1  1
29   0  1
..  .. ..
609  1  0
610  1  0
611  1  0
612  1  0
613  1  0
614  1  0
615  1  0
616  1  0
617  1  0
618  1  0
619  1  0
620  1  0
621  1  0
622  1  0
623  1  0
624  1  0
625  1  0
626  1  0
627  1  0
628  1  0
629  1  0
630  1  0
631  1  0
632  0  1
633  1  0
634  1  0
635  1  0
636  1  0
637  1  0
638  1  0

[639 rows x 2 columns]

In [63]:
diaper + diaper['status'].apply(mapper)

       0    1   c date   l status
0    NaN  NaN NaN  NaN NaN    NaN
1    NaN  NaN NaN  NaN NaN    NaN
2    NaN  NaN NaN  NaN NaN    NaN
3    NaN  NaN NaN  NaN NaN    NaN
4    NaN  NaN NaN  NaN NaN    NaN
5    NaN  NaN NaN  NaN NaN    NaN
6    NaN  NaN NaN  NaN NaN    NaN
7    NaN  NaN NaN  NaN NaN    NaN
8    NaN  NaN NaN  NaN NaN    NaN
9    NaN  NaN NaN  NaN NaN    NaN
10   NaN  NaN NaN  NaN NaN    NaN
11   NaN  NaN NaN  NaN NaN    NaN
12   NaN  NaN NaN  NaN NaN    NaN
13   NaN  NaN NaN  NaN NaN    NaN
14   NaN  NaN NaN  NaN NaN    NaN
15   NaN  NaN NaN  NaN NaN    NaN
16   NaN  NaN NaN  NaN NaN    NaN
17   NaN  NaN NaN  NaN NaN    NaN
18   NaN  NaN NaN  NaN NaN    NaN
19   NaN  NaN NaN  NaN NaN    NaN
20   NaN  NaN NaN  NaN NaN    NaN
21   NaN  NaN NaN  NaN NaN    NaN
22   NaN  NaN NaN  NaN NaN    NaN
23   NaN  NaN NaN  NaN NaN    NaN
24   NaN  NaN NaN  NaN NaN    NaN
25   NaN  NaN NaN  NaN NaN    NaN
26   NaN  NaN NaN  NaN NaN    NaN
27   NaN  NaN NaN  NaN NaN    NaN
28   NaN  NaN NaN  NaN NaN    NaN
29   NaN  NaN NaN  NaN NaN    NaN
..   ...  ...  ..  ...  ..    ...
609  NaN  NaN NaN  NaN NaN    NaN
610  NaN  NaN NaN  NaN NaN    NaN
611  NaN  NaN NaN  NaN NaN    NaN
612  NaN  NaN NaN  NaN NaN    NaN
613  NaN  NaN NaN  NaN NaN    NaN
614  NaN  NaN NaN  NaN NaN    NaN
615  NaN  NaN NaN  NaN NaN    NaN
616  NaN  NaN NaN  NaN NaN    NaN
617  NaN  NaN NaN  NaN NaN    NaN
618  NaN  NaN NaN  NaN NaN    NaN
619  NaN  NaN NaN  NaN NaN    NaN
620  NaN  NaN NaN  NaN NaN    NaN
621  NaN  NaN NaN  NaN NaN    NaN
622  NaN  NaN NaN  NaN NaN    NaN
623  NaN  NaN NaN  NaN NaN    NaN
624  NaN  NaN NaN  NaN NaN    NaN
625  NaN  NaN NaN  NaN NaN    NaN
626  NaN  NaN NaN  NaN NaN    NaN
627  NaN  NaN NaN  NaN NaN    NaN
628  NaN  NaN NaN  NaN NaN    NaN
629  NaN  NaN NaN  NaN NaN    NaN
630  NaN  NaN NaN  NaN NaN    NaN
631  NaN  NaN NaN  NaN NaN    NaN
632  NaN  NaN NaN  NaN NaN    NaN
633  NaN  NaN NaN  NaN NaN    NaN
634  NaN  NaN NaN  NaN NaN    NaN
635  NaN  NaN NaN  NaN NaN    NaN
636  NaN  NaN NaN  NaN NaN    NaN
637  NaN  NaN NaN  NaN NaN    NaN
638  NaN  NaN NaN  NaN NaN    NaN

[639 rows x 6 columns]

In [64]:
pd.concat([diaper, diaper['status'].apply(mapper)], axis=1)

                 date status  l  c  0  1
0    2016/11/13 17:00     嘘嘘  0  1  1  0
1    2016/11/13 19:48  嘘嘘+便便  0  1  1  1
2    2016/11/13 22:23     便便  0  1  0  1
3    2016/11/14 00:19     便便  0  1  0  1
4    2016/11/14 04:33     嘘嘘  0  1  1  0
5    2016/11/14 09:20     便便  0  1  0  1
6    2016/11/14 11:33     便便  0  1  0  1
7    2016/11/14 16:14     便便  0  1  0  1
8    2016/11/14 21:12  嘘嘘+便便  0  1  1  1
9    2016/11/14 23:12  嘘嘘+便便  0  1  1  1
10   2016/11/15 00:32  嘘嘘+便便  0  1  1  1
11   2016/11/15 03:45     干爽  0  1  1  1
12   2016/11/15 07:06     嘘嘘  0  1  1  0
13   2016/11/15 10:30  嘘嘘+便便  0  1  1  1
14   2016/11/15 10:39     便便  0  1  0  1
15   2016/11/15 11:40  嘘嘘+便便  0  1  1  1
16   2016/11/15 16:28     便便  0  1  0  1
17   2016/11/15 19:39  嘘嘘+便便  0  1  1  1
18   2016/11/15 23:11     便便  0  1  0  1
19   2016/11/16 02:25  嘘嘘+便便  0  1  1  1
20   2016/11/16 05:33     嘘嘘  0  1  1  0
21   2016/11/16 08:15  嘘嘘+便便  0  1  1  1
22   2016/11/16 12:09  嘘嘘+便便  0  1  1  1
23   2016/11/16 14:21     嘘嘘  0  1  1  0
24   2016/11/16 15:47  嘘嘘+便便  0  1  1  1
25   2016/11/16 18:46  嘘嘘+便便  0  1  1  1
26   2016/11/16 18:46     嘘嘘  0  1  1  0
27   2016/11/16 19:53     便便  0  1  0  1
28   2016/11/16 20:23  嘘嘘+便便  0  1  1  1
29   2016/11/16 21:53     便便  0  1  0  1
..                ...    ... .. .. .. ..
609  2017/02/13 06:03     嘘嘘  0  1  1  0
610  2017/02/13 08:05     嘘嘘  0  1  1  0
611  2017/02/13 12:40     嘘嘘  0  1  1  0
612  2017/02/13 04:47     嘘嘘  0  1  1  0
613  2017/02/13 10:00     嘘嘘  0  1  1  0
614  2017/02/14 06:39     嘘嘘  0  1  1  0
615  2017/02/14 08:34     嘘嘘  0  1  1  0
616  2017/02/14 11:57     嘘嘘  0  1  1  0
617  2017/02/14 04:13     嘘嘘  0  1  1  0
618  2017/02/14 07:02     嘘嘘  0  1  1  0
619  2017/02/14 09:10     嘘嘘  0  1  1  0
620  2017/02/15 03:42     嘘嘘  0  1  1  0
621  2017/02/15 08:00     嘘嘘  0  1  1  0
622  2017/02/15 12:01     嘘嘘  0  1  1  0
623  2017/02/15 04:06     嘘嘘  0  1  1  0
624  2017/02/15 05:42     嘘嘘  0  1  1  0
625  2017/02/15 10:43     嘘嘘  0  1  1  0
626  2017/02/16 06:12     嘘嘘  0  1  1  0
627  2017/02/16 10:28     嘘嘘  0  1  1  0
628  2017/02/16 12:52     嘘嘘  0  1  1  0
629  2017/02/16 05:39     嘘嘘  0  1  1  0
630  2017/02/16 08:18     嘘嘘  0  1  1  0
631  2017/02/17 06:49     嘘嘘  0  1  1  0
632  2017/02/17 07:13     便便  0  1  0  1
633  2017/02/17 10:31     嘘嘘  0  1  1  0
634  2017/02/17 02:00     嘘嘘  0  1  1  0
635  2017/02/17 06:23     嘘嘘  0  1  1  0
636  2017/02/18 12:49     嘘嘘  0  1  1  0
637  2017/02/18 08:33     嘘嘘  0  1  1  0
638  2017/02/18 03:44     嘘嘘  0  1  1  0

[639 rows x 6 columns]

In [65]:
diaper = pd.read_csv('data/diaper_data.csv')

def mapper(key):
    if key == '嘘嘘':
        return pd.Series(['1', '0'], index=['l', 'c'])
    elif key == '便便':
        return pd.Series(['0', '1'], index=['l', 'c'])
    else:
        return pd.Series(['1', '1'], index=['l', 'c'])
    
converted = diaper['status'].apply(mapper)

pd.concat([diaper, converted], axis=1)

    name              date status          note  l  c
0     心心  2016/11/13 17:00     嘘嘘           NaN  1  0
1     心心  2016/11/13 19:48  嘘嘘+便便           NaN  1  1
2     心心  2016/11/13 22:23     便便           NaN  0  1
3     心心  2016/11/14 00:19     便便  一点点，感觉很稀，穿厚点  0  1
4     心心  2016/11/14 04:33     嘘嘘           NaN  1  0
5     心心  2016/11/14 09:20     便便           NaN  0  1
6     心心  2016/11/14 11:33     便便           NaN  0  1
7     心心  2016/11/14 16:14     便便           NaN  0  1
8     心心  2016/11/14 21:12  嘘嘘+便便           NaN  1  1
9     心心  2016/11/14 23:12  嘘嘘+便便           NaN  1  1
10    心心  2016/11/15 00:32  嘘嘘+便便           有点稀  1  1
11    心心  2016/11/15 03:45     干爽           NaN  1  1
12    心心  2016/11/15 07:06     嘘嘘           NaN  1  0
13    心心  2016/11/15 10:30  嘘嘘+便便           NaN  1  1
14    心心  2016/11/15 10:39     便便           NaN  0  1
15    心心  2016/11/15 11:40  嘘嘘+便便           NaN  1  1
16    心心  2016/11/15 16:28     便便      有的稀，颜色金黄  0  1
17    心心  2016/11/15 19:39  嘘嘘+便便           NaN  1  1
18    心心  2016/11/15 23:11     便便           NaN  0  1
19    心心  2016/11/16 02:25  嘘嘘+便便   主要是小便，大便一点点  1  1
20    心心  2016/11/16 05:33     嘘嘘           NaN  1  0
21    心心  2016/11/16 08:15  嘘嘘+便便          小便较多  1  1
22    心心  2016/11/16 12:09  嘘嘘+便便           NaN  1  1
23    心心  2016/11/16 14:21     嘘嘘           NaN  1  0
24    心心  2016/11/16 15:47  嘘嘘+便便         一点点大便  1  1
25    心心  2016/11/16 18:46  嘘嘘+便便     换的时候又尿了一泡  1  1
26    心心  2016/11/16 18:46     嘘嘘           NaN  1  0
27    心心  2016/11/16 19:53     便便           NaN  0  1
28    心心  2016/11/16 20:23  嘘嘘+便便           NaN  1  1
29    心心  2016/11/16 21:53     便便           NaN  0  1
..   ...               ...    ...           ... .. ..
609   心心  2017/02/13 06:03     嘘嘘           NaN  1  0
610   心心  2017/02/13 08:05     嘘嘘           NaN  1  0
611   心心  2017/02/13 12:40     嘘嘘           NaN  1  0
612   心心  2017/02/13 04:47     嘘嘘           NaN  1  0
613   心心  2017/02/13 10:00     嘘嘘           NaN  1  0
614   心心  2017/02/14 06:39     嘘嘘           NaN  1  0
615   心心  2017/02/14 08:34     嘘嘘           NaN  1  0
616   心心  2017/02/14 11:57     嘘嘘           NaN  1  0
617   心心  2017/02/14 04:13     嘘嘘           NaN  1  0
618   心心  2017/02/14 07:02     嘘嘘           NaN  1  0
619   心心  2017/02/14 09:10     嘘嘘           NaN  1  0
620   心心  2017/02/15 03:42     嘘嘘           NaN  1  0
621   心心  2017/02/15 08:00     嘘嘘           NaN  1  0
622   心心  2017/02/15 12:01     嘘嘘           NaN  1  0
623   心心  2017/02/15 04:06     嘘嘘           NaN  1  0
624   心心  2017/02/15 05:42     嘘嘘           NaN  1  0
625   心心  2017/02/15 10:43     嘘嘘           NaN  1  0
626   心心  2017/02/16 06:12     嘘嘘           NaN  1  0
627   心心  2017/02/16 10:28     嘘嘘           NaN  1  0
628   心心  2017/02/16 12:52     嘘嘘           NaN  1  0
629   心心  2017/02/16 05:39     嘘嘘           NaN  1  0
630   心心  2017/02/16 08:18     嘘嘘           NaN  1  0
631   心心  2017/02/17 06:49     嘘嘘           NaN  1  0
632   心心  2017/02/17 07:13     便便           NaN  0  1
633   心心  2017/02/17 10:31     嘘嘘           NaN  1  0
634   心心  2017/02/17 02:00     嘘嘘           NaN  1  0
635   心心  2017/02/17 06:23     嘘嘘           NaN  1  0
636   心心  2017/02/18 12:49     嘘嘘           NaN  1  0
637   心心  2017/02/18 08:33     嘘嘘           NaN  1  0
638   心心  2017/02/18 03:44     嘘嘘           NaN  1  0

[639 rows x 6 columns]

In [66]:

diaper = pd.read_csv('data/diaper_data.csv', usecols=['date', 'status'])

def mapper(key):
    if key == '嘘嘘':
        return pd.Series(['1', '0'], index=['l', 'c'])
    elif key == '便便':
        return pd.Series(['0', '1'], index=['l', 'c'])
    else:
        return pd.Series(['1', '1'], index=['l', 'c'])
    
converted = diaper['status'].apply(mapper)

pd.concat([diaper, converted], axis=1)

                 date status  l  c
0    2016/11/13 17:00     嘘嘘  1  0
1    2016/11/13 19:48  嘘嘘+便便  1  1
2    2016/11/13 22:23     便便  0  1
3    2016/11/14 00:19     便便  0  1
4    2016/11/14 04:33     嘘嘘  1  0
5    2016/11/14 09:20     便便  0  1
6    2016/11/14 11:33     便便  0  1
7    2016/11/14 16:14     便便  0  1
8    2016/11/14 21:12  嘘嘘+便便  1  1
9    2016/11/14 23:12  嘘嘘+便便  1  1
10   2016/11/15 00:32  嘘嘘+便便  1  1
11   2016/11/15 03:45     干爽  1  1
12   2016/11/15 07:06     嘘嘘  1  0
13   2016/11/15 10:30  嘘嘘+便便  1  1
14   2016/11/15 10:39     便便  0  1
15   2016/11/15 11:40  嘘嘘+便便  1  1
16   2016/11/15 16:28     便便  0  1
17   2016/11/15 19:39  嘘嘘+便便  1  1
18   2016/11/15 23:11     便便  0  1
19   2016/11/16 02:25  嘘嘘+便便  1  1
20   2016/11/16 05:33     嘘嘘  1  0
21   2016/11/16 08:15  嘘嘘+便便  1  1
22   2016/11/16 12:09  嘘嘘+便便  1  1
23   2016/11/16 14:21     嘘嘘  1  0
24   2016/11/16 15:47  嘘嘘+便便  1  1
25   2016/11/16 18:46  嘘嘘+便便  1  1
26   2016/11/16 18:46     嘘嘘  1  0
27   2016/11/16 19:53     便便  0  1
28   2016/11/16 20:23  嘘嘘+便便  1  1
29   2016/11/16 21:53     便便  0  1
..                ...    ... .. ..
609  2017/02/13 06:03     嘘嘘  1  0
610  2017/02/13 08:05     嘘嘘  1  0
611  2017/02/13 12:40     嘘嘘  1  0
612  2017/02/13 04:47     嘘嘘  1  0
613  2017/02/13 10:00     嘘嘘  1  0
614  2017/02/14 06:39     嘘嘘  1  0
615  2017/02/14 08:34     嘘嘘  1  0
616  2017/02/14 11:57     嘘嘘  1  0
617  2017/02/14 04:13     嘘嘘  1  0
618  2017/02/14 07:02     嘘嘘  1  0
619  2017/02/14 09:10     嘘嘘  1  0
620  2017/02/15 03:42     嘘嘘  1  0
621  2017/02/15 08:00     嘘嘘  1  0
622  2017/02/15 12:01     嘘嘘  1  0
623  2017/02/15 04:06     嘘嘘  1  0
624  2017/02/15 05:42     嘘嘘  1  0
625  2017/02/15 10:43     嘘嘘  1  0
626  2017/02/16 06:12     嘘嘘  1  0
627  2017/02/16 10:28     嘘嘘  1  0
628  2017/02/16 12:52     嘘嘘  1  0
629  2017/02/16 05:39     嘘嘘  1  0
630  2017/02/16 08:18     嘘嘘  1  0
631  2017/02/17 06:49     嘘嘘  1  0
632  2017/02/17 07:13     便便  0  1
633  2017/02/17 10:31     嘘嘘  1  0
634  2017/02/17 02:00     嘘嘘  1  0
635  2017/02/17 06:23     嘘嘘  1  0
636  2017/02/18 12:49     嘘嘘  1  0
637  2017/02/18 08:33     嘘嘘  1  0
638  2017/02/18 03:44     嘘嘘  1  0

[639 rows x 4 columns]

In [68]:
diaper['date']=pd.to_datetime(diaper['date'],format='%Y/%m/%d %H:%M')

In [70]:
diaper = pd.concat([diaper, converted], axis=1)

In [71]:
diaper['date']=pd.to_datetime(diaper['date'],format='%Y/%m/%d %H:%M')

In [72]:
diaper

                   date status  l  c
0   2016-11-13 17:00:00     嘘嘘  1  0
1   2016-11-13 19:48:00  嘘嘘+便便  1  1
2   2016-11-13 22:23:00     便便  0  1
3   2016-11-14 00:19:00     便便  0  1
4   2016-11-14 04:33:00     嘘嘘  1  0
5   2016-11-14 09:20:00     便便  0  1
6   2016-11-14 11:33:00     便便  0  1
7   2016-11-14 16:14:00     便便  0  1
8   2016-11-14 21:12:00  嘘嘘+便便  1  1
9   2016-11-14 23:12:00  嘘嘘+便便  1  1
10  2016-11-15 00:32:00  嘘嘘+便便  1  1
11  2016-11-15 03:45:00     干爽  1  1
12  2016-11-15 07:06:00     嘘嘘  1  0
13  2016-11-15 10:30:00  嘘嘘+便便  1  1
14  2016-11-15 10:39:00     便便  0  1
15  2016-11-15 11:40:00  嘘嘘+便便  1  1
16  2016-11-15 16:28:00     便便  0  1
17  2016-11-15 19:39:00  嘘嘘+便便  1  1
18  2016-11-15 23:11:00     便便  0  1
19  2016-11-16 02:25:00  嘘嘘+便便  1  1
20  2016-11-16 05:33:00     嘘嘘  1  0
21  2016-11-16 08:15:00  嘘嘘+便便  1  1
22  2016-11-16 12:09:00  嘘嘘+便便  1  1
23  2016-11-16 14:21:00     嘘嘘  1  0
24  2016-11-16 15:47:00  嘘嘘+便便  1  1
25  2016-11-16 18:46:00  嘘嘘+便便  1  1
26  2016-11-16 18:46:00     嘘嘘  1  0
27  2016-11-16 19:53:00     便便  0  1
28  2016-11-16 20:23:00  嘘嘘+便便  1  1
29  2016-11-16 21:53:00     便便  0  1
..                  ...    ... .. ..
609 2017-02-13 06:03:00     嘘嘘  1  0
610 2017-02-13 08:05:00     嘘嘘  1  0
611 2017-02-13 12:40:00     嘘嘘  1  0
612 2017-02-13 04:47:00     嘘嘘  1  0
613 2017-02-13 10:00:00     嘘嘘  1  0
614 2017-02-14 06:39:00     嘘嘘  1  0
615 2017-02-14 08:34:00     嘘嘘  1  0
616 2017-02-14 11:57:00     嘘嘘  1  0
617 2017-02-14 04:13:00     嘘嘘  1  0
618 2017-02-14 07:02:00     嘘嘘  1  0
619 2017-02-14 09:10:00     嘘嘘  1  0
620 2017-02-15 03:42:00     嘘嘘  1  0
621 2017-02-15 08:00:00     嘘嘘  1  0
622 2017-02-15 12:01:00     嘘嘘  1  0
623 2017-02-15 04:06:00     嘘嘘  1  0
624 2017-02-15 05:42:00     嘘嘘  1  0
625 2017-02-15 10:43:00     嘘嘘  1  0
626 2017-02-16 06:12:00     嘘嘘  1  0
627 2017-02-16 10:28:00     嘘嘘  1  0
628 2017-02-16 12:52:00     嘘嘘  1  0
629 2017-02-16 05:39:00     嘘嘘  1  0
630 2017-02-16 08:18:00     嘘嘘  1  0
631 2017-02-17 06:49:00     嘘嘘  1  0
632 2017-02-17 07:13:00     便便  0  1
633 2017-02-17 10:31:00     嘘嘘  1  0
634 2017-02-17 02:00:00     嘘嘘  1  0
635 2017-02-17 06:23:00     嘘嘘  1  0
636 2017-02-18 12:49:00     嘘嘘  1  0
637 2017-02-18 08:33:00     嘘嘘  1  0
638 2017-02-18 03:44:00     嘘嘘  1  0

[639 rows x 4 columns]

In [73]:
diaper.index=diaper['date']

In [77]:
diaper.groupby(pd.TimeGrouper(freq='D'))

In [80]:
grouped = diaper.groupby(pd.TimeGrouper(freq='D'))

In [81]:
grouped.groups

{Timestamp('2016-11-13 00:00:00', freq='D'): 3,
 Timestamp('2016-11-14 00:00:00', freq='D'): 10,
 Timestamp('2016-11-15 00:00:00', freq='D'): 19,
 Timestamp('2016-11-16 00:00:00', freq='D'): 31,
 Timestamp('2016-11-17 00:00:00', freq='D'): 39,
 Timestamp('2016-11-18 00:00:00', freq='D'): 49,
 Timestamp('2016-11-19 00:00:00', freq='D'): 58,
 Timestamp('2016-11-20 00:00:00', freq='D'): 66,
 Timestamp('2016-11-21 00:00:00', freq='D'): 76,
 Timestamp('2016-11-22 00:00:00', freq='D'): 83,
 Timestamp('2016-11-23 00:00:00', freq='D'): 94,
 Timestamp('2016-11-24 00:00:00', freq='D'): 104,
 Timestamp('2016-11-25 00:00:00', freq='D'): 113,
 Timestamp('2016-11-26 00:00:00', freq='D'): 122,
 Timestamp('2016-11-27 00:00:00', freq='D'): 127,
 Timestamp('2016-11-28 00:00:00', freq='D'): 136,
 Timestamp('2016-11-29 00:00:00', freq='D'): 145,
 Timestamp('2016-11-30 00:00:00', freq='D'): 152,
 Timestamp('2016-12-01 00:00:00', freq='D'): 157,
 Timestamp('2016-12-02 00:00:00', freq='D'): 164,
 Timestamp('2016-12-03 00:00:00', freq='D'): 170,
 Timestamp('2016-12-04 00:00:00', freq='D'): 177,
 Timestamp('2016-12-05 00:00:00', freq='D'): 183,
 Timestamp('2016-12-06 00:00:00', freq='D'): 191,
 Timestamp('2016-12-07 00:00:00', freq='D'): 197,
 Timestamp('2016-12-08 00:00:00', freq='D'): 203,
 Timestamp('2016-12-09 00:00:00', freq='D'): 209,
 Timestamp('2016-12-10 00:00:00', freq='D'): 216,
 Timestamp('2016-12-11 00:00:00', freq='D'): 223,
 Timestamp('2016-12-12 00:00:00', freq='D'): 230,
 Timestamp('2016-12-13 00:00:00', freq='D'): 235,
 Timestamp('2016-12-14 00:00:00', freq='D'): 243,
 Timestamp('2016-12-15 00:00:00', freq='D'): 250,
 Timestamp('2016-12-16 00:00:00', freq='D'): 255,
 Timestamp('2016-12-17 00:00:00', freq='D'): 265,
 Timestamp('2016-12-18 00:00:00', freq='D'): 272,
 Timestamp('2016-12-19 00:00:00', freq='D'): 278,
 Timestamp('2016-12-20 00:00:00', freq='D'): 286,
 Timestamp('2016-12-21 00:00:00', freq='D'): 295,
 Timestamp('2016-12-22 00:00:00', freq='D'): 303,
 Timestamp('2016-12-23 00:00:00', freq='D'): 311,
 Timestamp('2016-12-24 00:00:00', freq='D'): 317,
 Timestamp('2016-12-25 00:00:00', freq='D'): 325,
 Timestamp('2016-12-26 00:00:00', freq='D'): 331,
 Timestamp('2016-12-27 00:00:00', freq='D'): 337,
 Timestamp('2016-12-28 00:00:00', freq='D'): 343,
 Timestamp('2016-12-29 00:00:00', freq='D'): 351,
 Timestamp('2016-12-30 00:00:00', freq='D'): 357,
 Timestamp('2016-12-31 00:00:00', freq='D'): 361,
 Timestamp('2017-01-01 00:00:00', freq='D'): 367,
 Timestamp('2017-01-02 00:00:00', freq='D'): 374,
 Timestamp('2017-01-03 00:00:00', freq='D'): 379,
 Timestamp('2017-01-04 00:00:00', freq='D'): 385,
 Timestamp('2017-01-05 00:00:00', freq='D'): 390,
 Timestamp('2017-01-06 00:00:00', freq='D'): 396,
 Timestamp('2017-01-07 00:00:00', freq='D'): 402,
 Timestamp('2017-01-08 00:00:00', freq='D'): 406,
 Timestamp('2017-01-09 00:00:00', freq='D'): 411,
 Timestamp('2017-01-10 00:00:00', freq='D'): 416,
 Timestamp('2017-01-11 00:00:00', freq='D'): 422,
 Timestamp('2017-01-12 00:00:00', freq='D'): 428,
 Timestamp('2017-01-13 00:00:00', freq='D'): 433,
 Timestamp('2017-01-14 00:00:00', freq='D'): 439,
 Timestamp('2017-01-15 00:00:00', freq='D'): 445,
 Timestamp('2017-01-16 00:00:00', freq='D'): 450,
 Timestamp('2017-01-17 00:00:00', freq='D'): 457,
 Timestamp('2017-01-18 00:00:00', freq='D'): 463,
 Timestamp('2017-01-19 00:00:00', freq='D'): 470,
 Timestamp('2017-01-20 00:00:00', freq='D'): 475,
 Timestamp('2017-01-21 00:00:00', freq='D'): 482,
 Timestamp('2017-01-22 00:00:00', freq='D'): 489,
 Timestamp('2017-01-23 00:00:00', freq='D'): 495,
 Timestamp('2017-01-24 00:00:00', freq='D'): 500,
 Timestamp('2017-01-25 00:00:00', freq='D'): 507,
 Timestamp('2017-01-26 00:00:00', freq='D'): 515,
 Timestamp('2017-01-27 00:00:00', freq='D'): 521,
 Timestamp('2017-01-28 00:00:00', freq='D'): 527,
 Timestamp('2017-01-29 00:00:00', freq='D'): 533,
 Timestamp('2017-01-30 00:00:00', freq='D'): 538,
 Timestamp('2017-01-31 00:00:00', freq='D'): 542,
 Timestamp('2017-02-01 00:00:00', freq='D'): 548,
 Timestamp('2017-02-02 00:00:00', freq='D'): 553,
 Timestamp('2017-02-03 00:00:00', freq='D'): 560,
 Timestamp('2017-02-04 00:00:00', freq='D'): 564,
 Timestamp('2017-02-05 00:00:00', freq='D'): 568,
 Timestamp('2017-02-06 00:00:00', freq='D'): 572,
 Timestamp('2017-02-07 00:00:00', freq='D'): 578,
 Timestamp('2017-02-08 00:00:00', freq='D'): 585,
 Timestamp('2017-02-09 00:00:00', freq='D'): 591,
 Timestamp('2017-02-10 00:00:00', freq='D'): 596,
 Timestamp('2017-02-11 00:00:00', freq='D'): 602,
 Timestamp('2017-02-12 00:00:00', freq='D'): 609,
 Timestamp('2017-02-13 00:00:00', freq='D'): 614,
 Timestamp('2017-02-14 00:00:00', freq='D'): 620,
 Timestamp('2017-02-15 00:00:00', freq='D'): 626,
 Timestamp('2017-02-16 00:00:00', freq='D'): 631,
 Timestamp('2017-02-17 00:00:00', freq='D'): 636,
 Timestamp('2017-02-18 00:00:00', freq='D'): 639}

In [82]:
pd.groupby(diaper,by=[diaper.index.date, diaper.index.l, diaper.index.c])

AttributeError: 'DatetimeIndex' object has no attribute 'l'

In [84]:
g = diaper.groupby(['l', 'c'])

In [86]:
g.groups

{('0', '1'): DatetimeIndex(['2016-11-13 22:23:00', '2016-11-14 00:19:00',
                '2016-11-14 09:20:00', '2016-11-14 11:33:00',
                '2016-11-14 16:14:00', '2016-11-15 10:39:00',
                '2016-11-15 16:28:00', '2016-11-15 23:11:00',
                '2016-11-16 19:53:00', '2016-11-16 21:53:00',
                '2016-11-16 23:24:00', '2016-11-17 07:49:00',
                '2016-11-17 11:38:00', '2016-11-17 17:46:00',
                '2016-11-17 18:24:00', '2016-11-18 14:20:00',
                '2016-11-18 17:09:00', '2016-11-19 10:23:00',
                '2016-11-19 13:40:00', '2016-11-20 01:50:00',
                '2016-11-20 17:29:00', '2016-11-21 01:28:00',
                '2016-11-22 02:15:00', '2016-11-22 11:00:00',
                '2016-11-24 10:39:00', '2016-11-26 12:33:00',
                '2016-11-29 09:50:00', '2016-12-05 10:01:00',
                '2016-12-16 07:18:00', '2016-12-17 03:49:00',
                '2016-12-17 03:09:00', '2016-12-21 09:46:00',
                '2016-12-23 08:20:00', '2016-12-28 04:37:00',
                '2016-12-29 04:26:00', '2016-12-30 08:05:00',
                '2017-01-01 03:30:00', '2017-01-02 04:29:00',
                '2017-01-04 09:53:00', '2017-01-12 11:05:00',
                '2017-01-13 09:12:00', '2017-01-14 10:02:00',
                '2017-01-21 08:49:00', '2017-01-25 11:17:00',
                '2017-01-26 11:17:00', '2017-02-03 08:10:00',
                '2017-02-07 05:47:00', '2017-02-07 11:20:00',
                '2017-02-09 04:12:00', '2017-02-09 07:54:00',
                '2017-02-10 04:14:00', '2017-02-12 03:20:00',
                '2017-02-17 07:13:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 ('1', '0'): DatetimeIndex(['2016-11-13 17:00:00', '2016-11-14 04:33:00',
                '2016-11-15 07:06:00', '2016-11-16 05:33:00',
                '2016-11-16 14:21:00', '2016-11-16 18:46:00',
                '2016-11-17 04:35:00', '2016-11-18 02:18:00',
                '2016-11-18 19:49:00', '2016-11-18 22:20:00',
                ...
                '2017-02-16 12:52:00', '2017-02-16 05:39:00',
                '2017-02-16 08:18:00', '2017-02-17 06:49:00',
                '2017-02-17 10:31:00', '2017-02-17 02:00:00',
                '2017-02-17 06:23:00', '2017-02-18 12:49:00',
                '2017-02-18 08:33:00', '2017-02-18 03:44:00'],
               dtype='datetime64[ns]', name=u'date', length=364, freq=None),
 ('1', '1'): DatetimeIndex(['2016-11-13 19:48:00', '2016-11-14 21:12:00',
                '2016-11-14 23:12:00', '2016-11-15 00:32:00',
                '2016-11-15 03:45:00', '2016-11-15 10:30:00',
                '2016-11-15 11:40:00', '2016-11-15 19:39:00',
                '2016-11-16 02:25:00', '2016-11-16 08:15:00',
                ...
                '2017-01-23 06:34:00', '2017-01-28 12:09:00',
                '2017-01-29 08:42:00', '2017-02-02 03:16:00',
                '2017-02-03 07:29:00', '2017-02-07 06:28:00',
                '2017-02-07 02:10:00', '2017-02-08 01:40:00',
                '2017-02-10 07:34:00', '2017-02-11 02:34:00'],
               dtype='datetime64[ns]', name=u'date', length=222, freq=None)}

In [91]:
g = diaper.groupby([diaper['date'].map(lambda x: x.day), 'l'])

In [92]:
g.groups

{(1,
  '0'): DatetimeIndex(['2017-01-01 03:30:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (1, '1'): DatetimeIndex(['2016-12-01 09:08:00', '2016-12-01 12:47:00',
                '2016-12-01 04:38:00', '2016-12-01 05:52:00',
                '2016-12-01 08:58:00', '2017-01-01 03:57:00',
                '2017-01-01 09:09:00', '2017-01-01 10:32:00',
                '2017-01-01 02:20:00', '2017-01-01 09:27:00',
                '2017-02-01 01:49:00', '2017-02-01 08:15:00',
                '2017-02-01 10:20:00', '2017-02-01 01:23:00',
                '2017-02-01 03:12:00', '2017-02-01 07:55:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (2,
  '0'): DatetimeIndex(['2017-01-02 04:29:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (2, '1'): DatetimeIndex(['2016-12-02 01:37:00', '2016-12-02 05:16:00',
                '2016-12-02 08:04:00', '2016-12-02 11:41:00',
                '2016-12-02 05:52:00', '2016-12-02 06:40:00',
                '2016-12-02 07:35:00', '2017-01-02 04:22:00',
                '2017-01-02 08:23:00', '2017-01-02 10:14:00',
                '2017-01-02 03:54:00', '2017-01-02 06:57:00',
                '2017-01-02 08:54:00', '2017-02-02 01:15:00',
                '2017-02-02 08:03:00', '2017-02-02 11:13:00',
                '2017-02-02 03:16:00', '2017-02-02 08:47:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (3,
  '0'): DatetimeIndex(['2017-02-03 08:10:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (3, '1'): DatetimeIndex(['2016-12-03 04:55:00', '2016-12-03 08:02:00',
                '2016-12-03 12:01:00', '2016-12-03 01:45:00',
                '2016-12-03 05:08:00', '2016-12-03 08:32:00',
                '2017-01-03 03:12:00', '2017-01-03 08:33:00',
                '2017-01-03 11:42:00', '2017-01-03 03:43:00',
                '2017-01-03 08:23:00', '2017-02-03 04:27:00',
                '2017-02-03 07:52:00', '2017-02-03 11:14:00',
                '2017-02-03 01:40:00', '2017-02-03 05:12:00',
                '2017-02-03 07:29:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (4,
  '0'): DatetimeIndex(['2017-01-04 09:53:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (4, '1'): DatetimeIndex(['2016-12-04 08:18:00', '2016-12-04 10:26:00',
                '2016-12-04 11:44:00', '2016-12-04 01:14:00',
                '2016-12-04 06:27:00', '2016-12-04 08:34:00',
                '2016-12-04 09:52:00', '2017-01-04 04:47:00',
                '2017-01-04 10:30:00', '2017-01-04 03:00:00',
                '2017-01-04 07:00:00', '2017-01-04 09:21:00',
                '2017-02-04 06:49:00', '2017-02-04 09:48:00',
                '2017-02-04 01:26:00', '2017-02-04 06:00:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (5,
  '0'): DatetimeIndex(['2016-12-05 10:01:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (5, '1'): DatetimeIndex(['2016-12-05 09:37:00', '2016-12-05 12:01:00',
                '2016-12-05 06:23:00', '2016-12-05 09:03:00',
                '2016-12-05 09:13:00', '2017-01-05 01:17:00',
                '2017-01-05 06:42:00', '2017-01-05 08:35:00',
                '2017-01-05 02:49:00', '2017-01-05 06:47:00',
                '2017-02-05 03:16:00', '2017-02-05 09:07:00',
                '2017-02-05 03:19:00', '2017-02-05 07:01:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (6, '1'): DatetimeIndex(['2016-12-06 05:56:00', '2016-12-06 06:18:00',
                '2016-12-06 10:57:00', '2016-12-06 11:58:00',
                '2016-12-06 03:41:00', '2016-12-06 04:19:00',
                '2016-12-06 07:36:00', '2016-12-06 11:10:00',
                '2017-01-06 12:25:00', '2017-01-06 08:21:00',
                '2017-01-06 10:49:00', '2017-01-06 01:53:00',
                '2017-01-06 06:45:00', '2017-01-06 10:17:00',
                '2017-02-06 02:00:00', '2017-02-06 08:08:00',
                '2017-02-06 11:59:00', '2017-02-06 06:27:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (7,
  '0'): DatetimeIndex(['2017-02-07 05:47:00', '2017-02-07 11:20:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (7, '1'): DatetimeIndex(['2016-12-07 02:00:00', '2016-12-07 09:40:00',
                '2016-12-07 11:29:00', '2016-12-07 01:13:00',
                '2016-12-07 03:25:00', '2016-12-07 06:34:00',
                '2017-01-07 05:11:00', '2017-01-07 09:00:00',
                '2017-01-07 01:00:00', '2017-01-07 04:30:00',
                '2017-01-07 07:19:00', '2017-01-07 09:37:00',
                '2017-02-07 06:28:00', '2017-02-07 10:30:00',
                '2017-02-07 02:10:00', '2017-02-07 06:48:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (8, '1'): DatetimeIndex(['2016-12-08 05:17:00', '2016-12-08 09:52:00',
                '2016-12-08 10:42:00', '2016-12-08 12:31:00',
                '2016-12-08 04:59:00', '2016-12-08 09:11:00',
                '2017-01-08 09:20:00', '2017-01-08 10:34:00',
                '2017-01-08 06:08:00', '2017-01-08 09:51:00',
                '2017-02-08 04:07:00', '2017-02-08 08:57:00',
                '2017-02-08 11:26:00', '2017-02-08 12:24:00',
                '2017-02-08 01:40:00', '2017-02-08 06:43:00',
                '2017-02-08 10:01:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (9,
  '0'): DatetimeIndex(['2017-02-09 04:12:00', '2017-02-09 07:54:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (9, '1'): DatetimeIndex(['2016-12-09 02:43:00', '2016-12-09 08:49:00',
                '2016-12-09 10:26:00', '2016-12-09 11:32:00',
                '2016-12-09 03:47:00', '2016-12-09 07:45:00',
                '2017-01-09 03:21:00', '2017-01-09 08:43:00',
                '2017-01-09 12:34:00', '2017-01-09 01:00:00',
                '2017-01-09 06:25:00', '2017-02-09 07:00:00',
                '2017-02-09 11:21:00', '2017-02-09 02:24:00',
                '2017-02-09 07:12:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (10,
  '0'): DatetimeIndex(['2017-02-10 04:14:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (10, '1'): DatetimeIndex(['2016-12-10 01:48:00', '2016-12-10 09:39:00',
                '2016-12-10 12:15:00', '2016-12-10 04:08:00',
                '2016-12-10 04:30:00', '2016-12-10 08:26:00',
                '2016-12-10 09:12:00', '2017-01-10 02:11:00',
                '2017-01-10 08:25:00', '2017-01-10 02:08:00',
                '2017-01-10 06:28:00', '2017-01-10 08:20:00',
                '2017-02-10 01:00:00', '2017-02-10 07:57:00',
                '2017-02-10 12:22:00', '2017-02-10 07:34:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (11, '1'): DatetimeIndex(['2016-12-11 01:03:00', '2016-12-11 09:57:00',
                '2016-12-11 11:26:00', '2016-12-11 12:29:00',
                '2016-12-11 04:17:00', '2016-12-11 06:49:00',
                '2016-12-11 11:38:00', '2017-01-11 01:59:00',
                '2017-01-11 07:39:00', '2017-01-11 08:24:00',
                '2017-01-11 11:44:00', '2017-01-11 04:28:00',
                '2017-01-11 07:10:00', '2017-02-11 02:50:00',
                '2017-02-11 05:46:00', '2017-02-11 09:20:00',
                '2017-02-11 01:50:00', '2017-02-11 02:34:00',
                '2017-02-11 06:40:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (12,
  '0'): DatetimeIndex(['2017-01-12 11:05:00', '2017-02-12 03:20:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (12, '1'): DatetimeIndex(['2016-12-12 06:57:00', '2016-12-12 09:46:00',
                '2016-12-12 11:38:00', '2016-12-12 04:59:00',
                '2016-12-12 06:22:00', '2016-12-12 08:36:00',
                '2016-12-12 09:45:00', '2017-01-12 01:15:00',
                '2017-01-12 05:35:00', '2017-01-12 10:05:00',
                '2017-01-12 02:51:00', '2017-01-12 06:12:00',
                '2017-02-12 04:51:00', '2017-02-12 09:06:00',
                '2017-02-12 11:50:00', '2017-02-12 01:45:00',
                '2017-02-12 05:00:00', '2017-02-12 08:01:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (13,
  '0'): DatetimeIndex(['2016-11-13 22:23:00', '2017-01-13 09:12:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (13, '1'): DatetimeIndex(['2016-11-13 17:00:00', '2016-11-13 19:48:00',
                '2016-12-13 01:03:00', '2016-12-13 06:18:00',
                '2016-12-13 10:14:00', '2016-12-13 01:38:00',
                '2016-12-13 06:01:00', '2017-01-13 01:25:00',
                '2017-01-13 08:30:00', '2017-01-13 02:12:00',
                '2017-01-13 05:51:00', '2017-02-13 06:03:00',
                '2017-02-13 08:05:00', '2017-02-13 12:40:00',
                '2017-02-13 04:47:00', '2017-02-13 10:00:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (14, '0'): DatetimeIndex(['2016-11-14 00:19:00', '2016-11-14 09:20:00',
                '2016-11-14 11:33:00', '2016-11-14 16:14:00',
                '2017-01-14 10:02:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (14, '1'): DatetimeIndex(['2016-11-14 04:33:00', '2016-11-14 21:12:00',
                '2016-11-14 23:12:00', '2016-12-14 02:37:00',
                '2016-12-14 08:58:00', '2016-12-14 10:09:00',
                '2016-12-14 10:51:00', '2016-12-14 05:19:00',
                '2016-12-14 05:19:00', '2016-12-14 09:04:00',
                '2016-12-14 10:06:00', '2017-01-14 12:52:00',
                '2017-01-14 08:27:00', '2017-01-14 12:23:00',
                '2017-01-14 05:40:00', '2017-01-14 07:20:00',
                '2017-02-14 06:39:00', '2017-02-14 08:34:00',
                '2017-02-14 11:57:00', '2017-02-14 04:13:00',
                '2017-02-14 07:02:00', '2017-02-14 09:10:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (15, '0'): DatetimeIndex(['2016-11-15 10:39:00', '2016-11-15 16:28:00',
                '2016-11-15 23:11:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (15, '1'): DatetimeIndex(['2016-11-15 00:32:00', '2016-11-15 03:45:00',
                '2016-11-15 07:06:00', '2016-11-15 10:30:00',
                '2016-11-15 11:40:00', '2016-11-15 19:39:00',
                '2016-12-15 03:41:00', '2016-12-15 08:28:00',
                '2016-12-15 11:31:00', '2016-12-15 03:38:00',
                '2016-12-15 06:55:00', '2016-12-15 07:59:00',
                '2016-12-15 10:48:00', '2017-01-15 04:54:00',
                '2017-01-15 08:41:00', '2017-01-15 11:50:00',
                '2017-01-15 04:40:00', '2017-01-15 07:19:00',
                '2017-01-15 10:06:00', '2017-02-15 03:42:00',
                '2017-02-15 08:00:00', '2017-02-15 12:01:00',
                '2017-02-15 04:06:00', '2017-02-15 05:42:00',
                '2017-02-15 10:43:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (16, '0'): DatetimeIndex(['2016-11-16 19:53:00', '2016-11-16 21:53:00',
                '2016-11-16 23:24:00', '2016-12-16 07:18:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (16, '1'): DatetimeIndex(['2016-11-16 02:25:00', '2016-11-16 05:33:00',
                '2016-11-16 08:15:00', '2016-11-16 12:09:00',
                '2016-11-16 14:21:00', '2016-11-16 15:47:00',
                '2016-11-16 18:46:00', '2016-11-16 18:46:00',
                '2016-11-16 20:23:00', '2016-12-16 03:47:00',
                '2016-12-16 10:56:00', '2016-12-16 03:04:00',
                '2016-12-16 06:38:00', '2017-01-16 02:44:00',
                '2017-01-16 08:00:00', '2017-01-16 10:47:00',
                '2017-01-16 03:35:00', '2017-01-16 07:00:00',
                '2017-02-16 06:12:00', '2017-02-16 10:28:00',
                '2017-02-16 12:52:00', '2017-02-16 05:39:00',
                '2017-02-16 08:18:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (17, '0'): DatetimeIndex(['2016-11-17 07:49:00', '2016-11-17 11:38:00',
                '2016-11-17 17:46:00', '2016-11-17 18:24:00',
                '2016-12-17 03:49:00', '2016-12-17 03:09:00',
                '2017-02-17 07:13:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (17, '1'): DatetimeIndex(['2016-11-17 04:35:00', '2016-11-17 11:04:00',
                '2016-11-17 14:27:00', '2016-11-17 23:32:00',
                '2016-12-17 03:20:00', '2016-12-17 07:19:00',
                '2016-12-17 08:47:00', '2016-12-17 10:34:00',
                '2016-12-17 12:18:00', '2016-12-17 02:11:00',
                '2016-12-17 07:00:00', '2016-12-17 09:00:00',
                '2017-01-17 12:02:00', '2017-01-17 04:55:00',
                '2017-01-17 08:41:00', '2017-01-17 10:56:00',
                '2017-01-17 01:39:00', '2017-01-17 06:47:00',
                '2017-01-17 08:37:00', '2017-02-17 06:49:00',
                '2017-02-17 10:31:00', '2017-02-17 02:00:00',
                '2017-02-17 06:23:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (18,
  '0'): DatetimeIndex(['2016-11-18 14:20:00', '2016-11-18 17:09:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (18, '1'): DatetimeIndex(['2016-11-18 02:18:00', '2016-11-18 04:30:00',
                '2016-11-18 07:35:00', '2016-11-18 10:27:00',
                '2016-11-18 11:27:00', '2016-11-18 19:49:00',
                '2016-11-18 22:20:00', '2016-11-18 23:55:00',
                '2016-12-18 03:34:00', '2016-12-18 08:01:00',
                '2016-12-18 10:38:00', '2016-12-18 12:16:00',
                '2016-12-18 05:23:00', '2016-12-18 07:13:00',
                '2016-12-18 09:41:00', '2017-01-18 01:52:00',
                '2017-01-18 08:15:00', '2017-01-18 09:12:00',
                '2017-01-18 11:37:00', '2017-01-18 05:07:00',
                '2017-01-18 08:16:00', '2017-02-18 12:49:00',
                '2017-02-18 08:33:00', '2017-02-18 03:44:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (19,
  '0'): DatetimeIndex(['2016-11-19 10:23:00', '2016-11-19 13:40:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (19, '1'): DatetimeIndex(['2016-11-19 03:19:00', '2016-11-19 07:13:00',
                '2016-11-19 11:17:00', '2016-11-19 17:40:00',
                '2016-11-19 17:52:00', '2016-11-19 21:31:00',
                '2016-11-19 23:55:00', '2016-12-19 04:18:00',
                '2016-12-19 09:45:00', '2016-12-19 11:07:00',
                '2016-12-19 02:45:00', '2016-12-19 06:46:00',
                '2016-12-19 10:41:00', '2017-01-19 05:14:00',
                '2017-01-19 08:10:00', '2017-01-19 09:47:00',
                '2017-01-19 11:27:00', '2017-01-19 02:54:00',
                '2017-01-19 04:36:00', '2017-01-19 08:13:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (20,
  '0'): DatetimeIndex(['2016-11-20 01:50:00', '2016-11-20 17:29:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (20, '1'): DatetimeIndex(['2016-11-20 01:27:00', '2016-11-20 06:06:00',
                '2016-11-20 12:34:00', '2016-11-20 14:03:00',
                '2016-11-20 15:44:00', '2016-11-20 21:39:00',
                '2016-12-20 01:40:00', '2016-12-20 03:10:00',
                '2016-12-20 05:09:00', '2016-12-20 06:27:00',
                '2016-12-20 08:55:00', '2016-12-20 11:55:00',
                '2016-12-20 06:34:00', '2016-12-20 07:51:00',
                '2017-01-20 02:08:00', '2017-01-20 06:24:00',
                '2017-01-20 08:49:00', '2017-01-20 01:34:00',
                '2017-01-20 07:59:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (21, '0'): DatetimeIndex(['2016-11-21 01:28:00', '2016-12-21 09:46:00',
                '2017-01-21 08:49:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (21, '1'): DatetimeIndex(['2016-11-21 01:10:00', '2016-11-21 06:10:00',
                '2016-11-21 06:17:00', '2016-11-21 10:34:00',
                '2016-11-21 13:01:00', '2016-11-21 16:16:00',
                '2016-11-21 18:16:00', '2016-11-21 09:03:00',
                '2016-11-21 09:16:00', '2016-12-21 12:12:00',
                '2016-12-21 05:13:00', '2016-12-21 08:38:00',
                '2016-12-21 11:39:00', '2016-12-21 02:00:00',
                '2016-12-21 06:40:00', '2016-12-21 08:28:00',
                '2016-12-21 09:58:00', '2017-01-21 12:28:00',
                '2017-01-21 07:50:00', '2017-01-21 10:44:00',
                '2017-01-21 03:03:00', '2017-01-21 04:59:00',
                '2017-01-21 07:48:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (22,
  '0'): DatetimeIndex(['2016-11-22 02:15:00', '2016-11-22 11:00:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (22, '1'): DatetimeIndex(['2016-11-22 02:10:00', '2016-11-22 05:25:00',
                '2016-11-22 10:00:00', '2016-11-22 01:27:00',
                '2016-11-22 07:43:00', '2016-12-22 02:55:00',
                '2016-12-22 06:40:00', '2016-12-22 09:39:00',
                '2016-12-22 10:46:00', '2016-12-22 01:14:00',
                '2016-12-22 03:30:00', '2016-12-22 07:10:00',
                '2016-12-22 09:05:00', '2017-01-22 01:13:00',
                '2017-01-22 06:12:00', '2017-01-22 09:33:00',
                '2017-01-22 11:47:00', '2017-01-22 04:53:00',
                '2017-01-22 05:29:00', '2017-01-22 07:20:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (23,
  '0'): DatetimeIndex(['2016-12-23 08:20:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (23, '1'): DatetimeIndex(['2016-11-23 12:18:00', '2016-11-23 12:50:00',
                '2016-11-23 08:02:00', '2016-11-23 10:19:00',
                '2016-11-23 11:25:00', '2016-11-23 12:31:00',
                '2016-11-23 04:00:00', '2016-11-23 08:46:00',
                '2016-11-23 09:37:00', '2016-11-23 10:30:00',
                '2016-11-23 10:44:00', '2016-12-23 02:10:00',
                '2016-12-23 05:24:00', '2016-12-23 07:53:00',
                '2016-12-23 10:39:00', '2016-12-23 01:00:00',
                '2016-12-23 04:14:00', '2016-12-23 08:25:00',
                '2017-01-23 03:33:00', '2017-01-23 08:06:00',
                '2017-01-23 11:04:00', '2017-01-23 02:39:00',
                '2017-01-23 04:32:00', '2017-01-23 06:34:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (24,
  '0'): DatetimeIndex(['2016-11-24 10:39:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (24, '1'): DatetimeIndex(['2016-11-24 03:46:00', '2016-11-24 06:06:00',
                '2016-11-24 09:06:00', '2016-11-24 09:53:00',
                '2016-11-24 10:22:00', '2016-11-24 02:10:00',
                '2016-11-24 04:45:00', '2016-11-24 06:22:00',
                '2016-11-24 10:05:00', '2016-12-24 02:36:00',
                '2016-12-24 06:46:00', '2016-12-24 08:59:00',
                '2016-12-24 10:47:00', '2016-12-24 03:21:00',
                '2016-12-24 08:03:00', '2017-01-24 04:20:00',
                '2017-01-24 11:00:00', '2017-01-24 12:50:00',
                '2017-01-24 05:10:00', '2017-01-24 07:40:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (25,
  '0'): DatetimeIndex(['2017-01-25 11:17:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (25, '1'): DatetimeIndex(['2016-11-25 02:42:00', '2016-11-25 06:32:00',
                '2016-11-25 10:19:00', '2016-11-25 11:21:00',
                '2016-11-25 02:47:00', '2016-11-25 03:40:00',
                '2016-11-25 06:22:00', '2016-11-25 09:15:00',
                '2016-11-25 10:33:00', '2016-12-25 02:51:00',
                '2016-12-25 07:57:00', '2016-12-25 08:53:00',
                '2016-12-25 12:02:00', '2016-12-25 05:01:00',
                '2016-12-25 06:10:00', '2016-12-25 08:09:00',
                '2016-12-25 09:55:00', '2017-01-25 02:21:00',
                '2017-01-25 07:03:00', '2017-01-25 09:35:00',
                '2017-01-25 02:40:00', '2017-01-25 06:09:00',
                '2017-01-25 09:20:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (26,

In [95]:
g = diaper.groupby([pd.TimeGrouper('D'), 'l', 'c'])

In [96]:
g.groups

{(Timestamp('2016-11-13 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-13 22:23:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-13 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-13 17:00:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-13 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-13 19:48:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-14 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-14 00:19:00', '2016-11-14 09:20:00',
                '2016-11-14 11:33:00', '2016-11-14 16:14:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-14 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-14 04:33:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-14 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-14 21:12:00', '2016-11-14 23:12:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-15 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-15 10:39:00', '2016-11-15 16:28:00',
                '2016-11-15 23:11:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-15 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-15 07:06:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-15 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-15 00:32:00', '2016-11-15 03:45:00',
                '2016-11-15 10:30:00', '2016-11-15 11:40:00',
                '2016-11-15 19:39:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-16 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-16 19:53:00', '2016-11-16 21:53:00',
                '2016-11-16 23:24:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-16 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-16 05:33:00', '2016-11-16 14:21:00',
                '2016-11-16 18:46:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-16 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-16 02:25:00', '2016-11-16 08:15:00',
                '2016-11-16 12:09:00', '2016-11-16 15:47:00',
                '2016-11-16 18:46:00', '2016-11-16 20:23:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-17 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-17 07:49:00', '2016-11-17 11:38:00',
                '2016-11-17 17:46:00', '2016-11-17 18:24:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-17 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-17 04:35:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-17 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-17 11:04:00', '2016-11-17 14:27:00',
                '2016-11-17 23:32:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-18 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-18 14:20:00', '2016-11-18 17:09:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-18 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-18 02:18:00', '2016-11-18 19:49:00',
                '2016-11-18 22:20:00', '2016-11-18 23:55:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-18 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-18 04:30:00', '2016-11-18 07:35:00',
                '2016-11-18 10:27:00', '2016-11-18 11:27:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-19 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-19 10:23:00', '2016-11-19 13:40:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-19 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-19 03:19:00', '2016-11-19 11:17:00',
                '2016-11-19 17:52:00', '2016-11-19 23:55:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-19 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-19 07:13:00', '2016-11-19 17:40:00',
                '2016-11-19 21:31:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-20 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-20 01:50:00', '2016-11-20 17:29:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-20 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-20 01:27:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-20 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-20 06:06:00', '2016-11-20 12:34:00',
                '2016-11-20 14:03:00', '2016-11-20 15:44:00',
                '2016-11-20 21:39:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-21 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-21 01:28:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-21 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-21 06:17:00', '2016-11-21 16:16:00',
                '2016-11-21 09:03:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-21 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-21 01:10:00', '2016-11-21 06:10:00',
                '2016-11-21 10:34:00', '2016-11-21 13:01:00',
                '2016-11-21 18:16:00', '2016-11-21 09:16:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-22 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-22 02:15:00', '2016-11-22 11:00:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-22 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-22 02:10:00', '2016-11-22 05:25:00',
                '2016-11-22 10:00:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-22 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-22 01:27:00', '2016-11-22 07:43:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-23 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-23 12:18:00', '2016-11-23 12:31:00',
                '2016-11-23 04:00:00', '2016-11-23 09:37:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-23 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-23 12:50:00', '2016-11-23 08:02:00',
                '2016-11-23 10:19:00', '2016-11-23 11:25:00',
                '2016-11-23 08:46:00', '2016-11-23 10:30:00',
                '2016-11-23 10:44:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-24 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-24 10:39:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-24 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-24 03:46:00', '2016-11-24 06:06:00',
                '2016-11-24 10:05:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-24 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-24 09:06:00', '2016-11-24 09:53:00',
                '2016-11-24 10:22:00', '2016-11-24 02:10:00',
                '2016-11-24 04:45:00', '2016-11-24 06:22:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-25 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-25 02:42:00', '2016-11-25 10:19:00',
                '2016-11-25 06:22:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-25 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-25 06:32:00', '2016-11-25 11:21:00',
                '2016-11-25 02:47:00', '2016-11-25 03:40:00',
                '2016-11-25 09:15:00', '2016-11-25 10:33:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-26 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-26 12:33:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-26 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-26 02:56:00', '2016-11-26 08:16:00',
                '2016-11-26 10:48:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-26 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-26 08:33:00', '2016-11-26 09:22:00',
                '2016-11-26 10:42:00', '2016-11-26 09:21:00',
                '2016-11-26 10:09:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-27 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-27 08:40:00', '2016-11-27 11:30:00',
                '2016-11-27 05:55:00', '2016-11-27 09:01:00',
                '2016-11-27 09:02:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-28 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-28 07:33:00', '2016-11-28 11:29:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-28 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-28 12:01:00', '2016-11-28 12:33:00',
                '2016-11-28 08:28:00', '2016-11-28 11:41:00',
                '2016-11-28 02:31:00', '2016-11-28 05:13:00',
                '2016-11-28 07:31:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-29 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-11-29 09:50:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-29 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-29 03:51:00', '2016-11-29 09:47:00',
                '2016-11-29 04:43:00', '2016-11-29 06:10:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-29 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-29 07:02:00', '2016-11-29 10:36:00',
                '2016-11-29 03:44:00', '2016-11-29 11:35:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-30 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-11-30 12:29:00', '2016-11-30 11:17:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-11-30 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-11-30 07:43:00', '2016-11-30 09:14:00',
                '2016-11-30 01:00:00', '2016-11-30 06:30:00',
                '2016-11-30 09:43:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-01 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-01 12:47:00', '2016-12-01 05:52:00',
                '2016-12-01 08:58:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-01 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-01 09:08:00', '2016-12-01 04:38:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-02 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-02 01:37:00', '2016-12-02 06:40:00',
                '2016-12-02 07:35:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-02 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-02 05:16:00', '2016-12-02 08:04:00',
                '2016-12-02 11:41:00', '2016-12-02 05:52:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-03 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-03 08:32:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-03 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-03 04:55:00', '2016-12-03 08:02:00',
                '2016-12-03 12:01:00', '2016-12-03 01:45:00',
                '2016-12-03 05:08:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-04 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-04 10:26:00', '2016-12-04 01:14:00',
                '2016-12-04 08:34:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-04 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-04 08:18:00', '2016-12-04 11:44:00',
                '2016-12-04 06:27:00', '2016-12-04 09:52:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-05 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-12-05 10:01:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-05 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-05 06:23:00', '2016-12-05 09:03:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-05 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-05 09:37:00', '2016-12-05 12:01:00',
                '2016-12-05 09:13:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-06 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-06 05:56:00', '2016-12-06 10:57:00',
                '2016-12-06 03:41:00', '2016-12-06 04:19:00',
                '2016-12-06 07:36:00', '2016-12-06 11:10:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-06 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-06 06:18:00', '2016-12-06 11:58:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-07 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-07 02:00:00', '2016-12-07 09:40:00',
                '2016-12-07 11:29:00', '2016-12-07 01:13:00',
                '2016-12-07 03:25:00', '2016-12-07 06:34:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-08 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-08 05:17:00', '2016-12-08 10:42:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-08 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-08 09:52:00', '2016-12-08 12:31:00',
                '2016-12-08 04:59:00', '2016-12-08 09:11:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-09 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-09 08:49:00', '2016-12-09 07:45:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-09 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-09 02:43:00', '2016-12-09 10:26:00',
                '2016-12-09 11:32:00', '2016-12-09 03:47:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-10 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-10 12:15:00', '2016-12-10 04:08:00',
                '2016-12-10 08:26:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-10 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-10 01:48:00', '2016-12-10 09:39:00',
                '2016-12-10 04:30:00', '2016-12-10 09:12:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-11 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-11 11:26:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-11 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-11 01:03:00', '2016-12-11 09:57:00',
                '2016-12-11 12:29:00', '2016-12-11 04:17:00',
                '2016-12-11 06:49:00', '2016-12-11 11:38:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-12 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-12 06:57:00', '2016-12-12 09:46:00',
                '2016-12-12 11:38:00', '2016-12-12 04:59:00',
                '2016-12-12 06:22:00', '2016-12-12 08:36:00',
                '2016-12-12 09:45:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-13 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-13 06:18:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-13 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-13 01:03:00', '2016-12-13 10:14:00',
                '2016-12-13 01:38:00', '2016-12-13 06:01:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-14 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-14 08:58:00', '2016-12-14 05:19:00',
                '2016-12-14 09:04:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-14 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-14 02:37:00', '2016-12-14 10:09:00',
                '2016-12-14 10:51:00', '2016-12-14 05:19:00',
                '2016-12-14 10:06:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-15 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-15 03:41:00', '2016-12-15 03:38:00',
                '2016-12-15 10:48:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-15 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-15 08:28:00', '2016-12-15 11:31:00',
                '2016-12-15 06:55:00', '2016-12-15 07:59:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-16 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-12-16 07:18:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-16 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-16 03:47:00', '2016-12-16 03:04:00',
                '2016-12-16 06:38:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-16 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-16 10:56:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-17 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-12-17 03:49:00', '2016-12-17 03:09:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-17 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-17 03:20:00', '2016-12-17 07:19:00',
                '2016-12-17 12:18:00', '2016-12-17 02:11:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-17 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-17 08:47:00', '2016-12-17 10:34:00',
                '2016-12-17 07:00:00', '2016-12-17 09:00:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-18 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-18 03:34:00', '2016-12-18 12:16:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-18 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-18 08:01:00', '2016-12-18 10:38:00',
                '2016-12-18 05:23:00', '2016-12-18 07:13:00',
                '2016-12-18 09:41:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-19 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-19 10:41:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-19 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-19 04:18:00', '2016-12-19 09:45:00',
                '2016-12-19 11:07:00', '2016-12-19 02:45:00',
                '2016-12-19 06:46:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-20 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-20 01:40:00', '2016-12-20 11:55:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-20 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-20 03:10:00', '2016-12-20 05:09:00',
                '2016-12-20 06:27:00', '2016-12-20 08:55:00',
                '2016-12-20 06:34:00', '2016-12-20 07:51:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-21 00:00:00'),
  '0',
  '1'): DatetimeIndex(['2016-12-21 09:46:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-21 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-21 12:12:00', '2016-12-21 08:38:00',
                '2016-12-21 02:00:00', '2016-12-21 06:40:00',
                '2016-12-21 08:28:00', '2016-12-21 09:58:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-21 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-21 05:13:00', '2016-12-21 11:39:00'], dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-22 00:00:00'),
  '1',
  '0'): DatetimeIndex(['2016-12-22 02:55:00', '2016-12-22 03:30:00',
                '2016-12-22 09:05:00'],
               dtype='datetime64[ns]', name=u'date', freq=None),
 (Timestamp('2016-12-22 00:00:00'),
  '1',
  '1'): DatetimeIndex(['2016-12-22 06:40:00', '2016-12-22 09:39:00',

In [97]:
grouped = diaper.groupby(pd.TimeGrouper('D'))
grouped.aggregate(np.sum)

,status,l,c
date,,,
2016-11-13,嘘嘘嘘嘘+便便便便,110,011
2016-11-14,便便嘘嘘便便便便便便嘘嘘+便便嘘嘘+便便,0100011,1011111
2016-11-15,嘘嘘+便便干爽嘘嘘嘘嘘+便便便便嘘嘘+便便便便嘘嘘+便便便便,111101010,110111111
2016-11-16,嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘便便嘘嘘+便便便便便便,111111110100,101101101111
2016-11-17,嘘嘘便便嘘嘘+便便便便嘘嘘+便便便便便便嘘嘘+便便,10101001,01111111
2016-11-18,嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便便便便便嘘嘘嘘嘘嘘嘘,1111100111,0111111000
2016-11-19,嘘嘘嘘嘘+便便便便嘘嘘便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘,110101111,011011010
2016-11-20,嘘嘘便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便便便嘘嘘+便便,10111101,01111111
2016-11-21,嘘嘘+便便便便嘘嘘+便便嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便,1011111111,1110011101
2016-11-22,嘘嘘+便便嘘嘘便便嘘嘘嘘嘘+便便嘘嘘便便,1101110,1010101
2016-11-23,嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘嘘嘘+便便,11111111111,01101111001
2016-11-24,嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便便便,1111111110,1010111011
2016-11-25,嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便,111111111,011011011
2016-11-26,嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘便便,111111110,001111101
2016-11-27,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便,11111,11111
2016-11-28,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘+便便,111111111,111010111
2016-11-29,嘘嘘+便便嘘嘘嘘嘘嘘嘘嘘嘘+便便嘘嘘便便嘘嘘+便便嘘嘘+便便,111111011,100010111
2016-11-30,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘,1111111,1111100
2016-12-01,嘘嘘+便便嘘嘘嘘嘘嘘嘘+便便嘘嘘,11111,10010
2016-12-02,嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便,1111111,0110011
2016-12-03,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便,111111,111101
2016-12-04,嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘嘘嘘+便便,1111111,0110101
2016-12-05,嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便便便嘘嘘+便便,111101,001111
2016-12-06,嘘嘘嘘嘘嘘嘘嘘嘘+便便嘘嘘嘘嘘嘘嘘嘘嘘+便便,11111111,00010001
2016-12-07,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便,111111,111111
2016-12-08,嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便,111111,101101
2016-12-09,嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便,111111,110011
2016-12-10,嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘,1111111,1010110
2016-12-11,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘嘘嘘+便便嘘嘘+便便,1111111,1111011
2016-12-12,嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便嘘嘘+便便,1111111,1111111
...,...,...,...
2017-01-20,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,11111,00000
2017-01-21,嘘嘘嘘嘘嘘嘘嘘嘘便便嘘嘘嘘嘘,1111011,0000100
2017-01-22,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,1111111,0000000
2017-01-23,嘘嘘嘘嘘嘘嘘嘘嘘+便便嘘嘘+便便嘘嘘,111111,000110
2017-01-24,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,11111,00000
2017-01-25,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘便便,1111110,0000001
2017-01-26,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘便便,11111110,00000001
2017-01-27,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,111111,000000
2017-01-28,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘+便便,111111,000001
2017-01-29,嘘嘘嘘嘘嘘嘘嘘嘘+便便嘘嘘嘘嘘,111111,000100
2017-01-30,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,11111,00000
2017-01-31,嘘嘘嘘嘘嘘嘘嘘嘘,1111,0000
2017-02-01,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,111111,000000
2017-02-02,嘘嘘嘘嘘+便便嘘嘘嘘嘘嘘嘘,11111,01000
2017-02-03,嘘嘘嘘嘘嘘嘘嘘嘘+便便嘘嘘便便嘘嘘,1111101,0001010
2017-02-04,嘘嘘嘘嘘嘘嘘嘘嘘,1111,0000
2017-02-05,嘘嘘嘘嘘嘘嘘嘘嘘,1111,0000
2017-02-06,嘘嘘嘘嘘嘘嘘嘘嘘,1111,0000
2017-02-07,嘘嘘+便便便便嘘嘘+便便嘘嘘嘘嘘便便,101110,111001
2017-02-08,嘘嘘+便便嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,1111111,1000000
2017-02-09,嘘嘘便便嘘嘘嘘嘘便便嘘嘘,101101,010010
2017-02-10,嘘嘘便便嘘嘘+便便嘘嘘嘘嘘,10111,01100
2017-02-11,嘘嘘嘘嘘+便便嘘嘘嘘嘘嘘嘘嘘嘘,111111,010000
2017-02-12,嘘嘘便便嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,1011111,0100000
2017-02-13,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,11111,00000
2017-02-14,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,111111,000000
2017-02-15,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,111111,000000
2017-02-16,嘘嘘嘘嘘嘘嘘嘘嘘嘘嘘,11111,00000
2017-02-17,嘘嘘嘘嘘嘘嘘便便嘘嘘,11101,00010
2017-02-18,嘘嘘嘘嘘嘘嘘,111,000

In [98]:

diaper = pd.read_csv('data/diaper_data.csv', usecols=['date', 'status'])
diaper['date'] = pd.to_datetime(diaper['date'],format='%Y/%m/%d %H:%M')

def mapper(key):
    if key == '嘘嘘':
        return pd.Series([1, 0], index=['l', 'c'])
    elif key == '便便':
        return pd.Series([0, 1], index=['l', 'c'])
    else:
        return pd.Series([1, 1], index=['l', 'c'])
    

converted = diaper['status'].apply(mapper)
diaper = pd.concat([diaper, converted], axis=1)

grouped = diaper.groupby(pd.TimeGrouper('D'))
grouped.aggregate(np.sum)

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [99]:
diaper = pd.read_csv('data/diaper_data.csv', usecols=['date', 'status'])
diaper['date'] = pd.to_datetime(diaper['date'],format='%Y/%m/%d %H:%M')

def mapper(key):
    if key == '嘘嘘':
        return pd.Series([1, 0], index=['l', 'c'])
    elif key == '便便':
        return pd.Series([0, 1], index=['l', 'c'])
    else:
        return pd.Series([1, 1], index=['l', 'c'])
    

converted = diaper['status'].apply(mapper)
diaper = pd.concat([diaper, converted], axis=1)
diaper.index=diaper['date']

grouped = diaper.groupby(pd.TimeGrouper('D'))
grouped.aggregate(np.sum)

             l  c
date
2016-11-13   2  2
2016-11-14   3  6
2016-11-15   6  8
2016-11-16   9  9
2016-11-17   4  7
2016-11-18   8  6
2016-11-19   7  5
2016-11-20   6  7
2016-11-21   9  7
2016-11-22   5  4
2016-11-23  11  7
2016-11-24   9  7
2016-11-25   9  6
2016-11-26   8  6
2016-11-27   5  5
2016-11-28   9  7
2016-11-29   8  5
2016-11-30   7  5
2016-12-01   5  2
2016-12-02   7  4
2016-12-03   6  5
2016-12-04   7  4
2016-12-05   5  4
2016-12-06   8  2
2016-12-07   6  6
2016-12-08   6  4
2016-12-09   6  4
2016-12-10   7  4
2016-12-11   7  6
2016-12-12   7  7
...         .. ..
2017-01-20   5  0
2017-01-21   6  1
2017-01-22   7  0
2017-01-23   6  2
2017-01-24   5  0
2017-01-25   6  1
2017-01-26   7  1
2017-01-27   6  0
2017-01-28   6  1
2017-01-29   6  1
2017-01-30   5  0
2017-01-31   4  0
2017-02-01   6  0
2017-02-02   5  1
2017-02-03   6  2
2017-02-04   4  0
2017-02-05   4  0
2017-02-06   4  0
2017-02-07   4  4
2017-02-08   7  1
2017-02-09   4  2
2017-02-10   4  2
2017-02-11   6  1
2017-02-12   6  1
2017-02-13   5  0
2017-02-14   6  0
2017-02-15   6  0
2017-02-16   5  0
2017-02-17   4  1
2017-02-18   3  0

[98 rows x 2 columns]

In [100]:
grouped.groups

{Timestamp('2016-11-13 00:00:00', freq='D'): 3,
 Timestamp('2016-11-14 00:00:00', freq='D'): 10,
 Timestamp('2016-11-15 00:00:00', freq='D'): 19,
 Timestamp('2016-11-16 00:00:00', freq='D'): 31,
 Timestamp('2016-11-17 00:00:00', freq='D'): 39,
 Timestamp('2016-11-18 00:00:00', freq='D'): 49,
 Timestamp('2016-11-19 00:00:00', freq='D'): 58,
 Timestamp('2016-11-20 00:00:00', freq='D'): 66,
 Timestamp('2016-11-21 00:00:00', freq='D'): 76,
 Timestamp('2016-11-22 00:00:00', freq='D'): 83,
 Timestamp('2016-11-23 00:00:00', freq='D'): 94,
 Timestamp('2016-11-24 00:00:00', freq='D'): 104,
 Timestamp('2016-11-25 00:00:00', freq='D'): 113,
 Timestamp('2016-11-26 00:00:00', freq='D'): 122,
 Timestamp('2016-11-27 00:00:00', freq='D'): 127,
 Timestamp('2016-11-28 00:00:00', freq='D'): 136,
 Timestamp('2016-11-29 00:00:00', freq='D'): 145,
 Timestamp('2016-11-30 00:00:00', freq='D'): 152,
 Timestamp('2016-12-01 00:00:00', freq='D'): 157,
 Timestamp('2016-12-02 00:00:00', freq='D'): 164,
 Timestamp('2016-12-03 00:00:00', freq='D'): 170,
 Timestamp('2016-12-04 00:00:00', freq='D'): 177,
 Timestamp('2016-12-05 00:00:00', freq='D'): 183,
 Timestamp('2016-12-06 00:00:00', freq='D'): 191,
 Timestamp('2016-12-07 00:00:00', freq='D'): 197,
 Timestamp('2016-12-08 00:00:00', freq='D'): 203,
 Timestamp('2016-12-09 00:00:00', freq='D'): 209,
 Timestamp('2016-12-10 00:00:00', freq='D'): 216,
 Timestamp('2016-12-11 00:00:00', freq='D'): 223,
 Timestamp('2016-12-12 00:00:00', freq='D'): 230,
 Timestamp('2016-12-13 00:00:00', freq='D'): 235,
 Timestamp('2016-12-14 00:00:00', freq='D'): 243,
 Timestamp('2016-12-15 00:00:00', freq='D'): 250,
 Timestamp('2016-12-16 00:00:00', freq='D'): 255,
 Timestamp('2016-12-17 00:00:00', freq='D'): 265,
 Timestamp('2016-12-18 00:00:00', freq='D'): 272,
 Timestamp('2016-12-19 00:00:00', freq='D'): 278,
 Timestamp('2016-12-20 00:00:00', freq='D'): 286,
 Timestamp('2016-12-21 00:00:00', freq='D'): 295,
 Timestamp('2016-12-22 00:00:00', freq='D'): 303,
 Timestamp('2016-12-23 00:00:00', freq='D'): 311,
 Timestamp('2016-12-24 00:00:00', freq='D'): 317,
 Timestamp('2016-12-25 00:00:00', freq='D'): 325,
 Timestamp('2016-12-26 00:00:00', freq='D'): 331,
 Timestamp('2016-12-27 00:00:00', freq='D'): 337,
 Timestamp('2016-12-28 00:00:00', freq='D'): 343,
 Timestamp('2016-12-29 00:00:00', freq='D'): 351,
 Timestamp('2016-12-30 00:00:00', freq='D'): 357,
 Timestamp('2016-12-31 00:00:00', freq='D'): 361,
 Timestamp('2017-01-01 00:00:00', freq='D'): 367,
 Timestamp('2017-01-02 00:00:00', freq='D'): 374,
 Timestamp('2017-01-03 00:00:00', freq='D'): 379,
 Timestamp('2017-01-04 00:00:00', freq='D'): 385,
 Timestamp('2017-01-05 00:00:00', freq='D'): 390,
 Timestamp('2017-01-06 00:00:00', freq='D'): 396,
 Timestamp('2017-01-07 00:00:00', freq='D'): 402,
 Timestamp('2017-01-08 00:00:00', freq='D'): 406,
 Timestamp('2017-01-09 00:00:00', freq='D'): 411,
 Timestamp('2017-01-10 00:00:00', freq='D'): 416,
 Timestamp('2017-01-11 00:00:00', freq='D'): 422,
 Timestamp('2017-01-12 00:00:00', freq='D'): 428,
 Timestamp('2017-01-13 00:00:00', freq='D'): 433,
 Timestamp('2017-01-14 00:00:00', freq='D'): 439,
 Timestamp('2017-01-15 00:00:00', freq='D'): 445,
 Timestamp('2017-01-16 00:00:00', freq='D'): 450,
 Timestamp('2017-01-17 00:00:00', freq='D'): 457,
 Timestamp('2017-01-18 00:00:00', freq='D'): 463,
 Timestamp('2017-01-19 00:00:00', freq='D'): 470,
 Timestamp('2017-01-20 00:00:00', freq='D'): 475,
 Timestamp('2017-01-21 00:00:00', freq='D'): 482,
 Timestamp('2017-01-22 00:00:00', freq='D'): 489,
 Timestamp('2017-01-23 00:00:00', freq='D'): 495,
 Timestamp('2017-01-24 00:00:00', freq='D'): 500,
 Timestamp('2017-01-25 00:00:00', freq='D'): 507,
 Timestamp('2017-01-26 00:00:00', freq='D'): 515,
 Timestamp('2017-01-27 00:00:00', freq='D'): 521,
 Timestamp('2017-01-28 00:00:00', freq='D'): 527,
 Timestamp('2017-01-29 00:00:00', freq='D'): 533,
 Timestamp('2017-01-30 00:00:00', freq='D'): 538,
 Timestamp('2017-01-31 00:00:00', freq='D'): 542,
 Timestamp('2017-02-01 00:00:00', freq='D'): 548,
 Timestamp('2017-02-02 00:00:00', freq='D'): 553,
 Timestamp('2017-02-03 00:00:00', freq='D'): 560,
 Timestamp('2017-02-04 00:00:00', freq='D'): 564,
 Timestamp('2017-02-05 00:00:00', freq='D'): 568,
 Timestamp('2017-02-06 00:00:00', freq='D'): 572,
 Timestamp('2017-02-07 00:00:00', freq='D'): 578,
 Timestamp('2017-02-08 00:00:00', freq='D'): 585,
 Timestamp('2017-02-09 00:00:00', freq='D'): 591,
 Timestamp('2017-02-10 00:00:00', freq='D'): 596,
 Timestamp('2017-02-11 00:00:00', freq='D'): 602,
 Timestamp('2017-02-12 00:00:00', freq='D'): 609,
 Timestamp('2017-02-13 00:00:00', freq='D'): 614,
 Timestamp('2017-02-14 00:00:00', freq='D'): 620,
 Timestamp('2017-02-15 00:00:00', freq='D'): 626,
 Timestamp('2017-02-16 00:00:00', freq='D'): 631,
 Timestamp('2017-02-17 00:00:00', freq='D'): 636,
 Timestamp('2017-02-18 00:00:00', freq='D'): 639}

In [101]:

diaper = pd.read_csv('data/diaper_data.csv', usecols=['date', 'status'])
diaper['date'] = pd.to_datetime(diaper['date'], format='%Y/%m/%d %H:%M')
diaper.index=diaper['date']

def mapper(key):
    if key == '嘘嘘':
        return pd.Series([1, 0], index=['urinate', 'stool'])
    elif key == '便便':
        return pd.Series([0, 1], index=['urinate', 'stool'])
    else:
        return pd.Series([1, 1], index=['urinate', 'stool'])
    

converted = diaper['status'].apply(mapper)
diaper = pd.concat([diaper, converted], axis=1)


grouped = diaper.groupby(pd.TimeGrouper('D'))
grouped.aggregate(np.sum)

            urinate  stool
date
2016-11-13        2      2
2016-11-14        3      6
2016-11-15        6      8
2016-11-16        9      9
2016-11-17        4      7
2016-11-18        8      6
2016-11-19        7      5
2016-11-20        6      7
2016-11-21        9      7
2016-11-22        5      4
2016-11-23       11      7
2016-11-24        9      7
2016-11-25        9      6
2016-11-26        8      6
2016-11-27        5      5
2016-11-28        9      7
2016-11-29        8      5
2016-11-30        7      5
2016-12-01        5      2
2016-12-02        7      4
2016-12-03        6      5
2016-12-04        7      4
2016-12-05        5      4
2016-12-06        8      2
2016-12-07        6      6
2016-12-08        6      4
2016-12-09        6      4
2016-12-10        7      4
2016-12-11        7      6
2016-12-12        7      7
...             ...    ...
2017-01-20        5      0
2017-01-21        6      1
2017-01-22        7      0
2017-01-23        6      2
2017-01-24        5      0
2017-01-25        6      1
2017-01-26        7      1
2017-01-27        6      0
2017-01-28        6      1
2017-01-29        6      1
2017-01-30        5      0
2017-01-31        4      0
2017-02-01        6      0
2017-02-02        5      1
2017-02-03        6      2
2017-02-04        4      0
2017-02-05        4      0
2017-02-06        4      0
2017-02-07        4      4
2017-02-08        7      1
2017-02-09        4      2
2017-02-10        4      2
2017-02-11        6      1
2017-02-12        6      1
2017-02-13        5      0
2017-02-14        6      0
2017-02-15        6      0
2017-02-16        5      0
2017-02-17        4      1
2017-02-18        3      0

[98 rows x 2 columns]

In [102]:
result = grouped.aggregate(np.sum)

In [104]:
result.to_csv('diaper_normolized.csv')

In [106]:

sleeping = pd.read_csv('data/sleeping_data.csv', usecols=['date', 'length'])
sleeping['date'] = pd.to_datetime(sleeping['date'], format="%Y/%m/%d %H:%M")
sleeping.index = sleeping['date']

grouped = sleeping.groupby(pd.TimeGrouper('D'))
result = grouped.aggregate(np.sum)

In [107]:
result

            length
date
2016-11-13     118
2016-11-14     942
2016-11-15    1041
2016-11-16     836
2016-11-17     810
2016-11-18     993
2016-11-19    1021
2016-11-20    1063
2016-11-21    1064
2016-11-22     938
2016-11-23     900
2016-11-24    1078
2016-11-25    1044
2016-11-26     916
2016-11-27     772
2016-11-28     942
2016-11-29     782
2016-11-30     671
2016-12-01    1007
2016-12-02     949
2016-12-03     883
2016-12-04     813
2016-12-05     846
2016-12-06     753
2016-12-07     938
2016-12-08     706
2016-12-09     778
2016-12-10     849
2016-12-11     843
2016-12-12     747
...            ...
2017-01-20     797
2017-01-21    1049
2017-01-22     880
2017-01-23     754
2017-01-24     688
2017-01-25     760
2017-01-26     855
2017-01-27     768
2017-01-28     920
2017-01-29     730
2017-01-30     904
2017-01-31     805
2017-02-01     811
2017-02-02     934
2017-02-03     760
2017-02-04     603
2017-02-05     933
2017-02-06     747
2017-02-07     736
2017-02-08     787
2017-02-09     671
2017-02-10     860
2017-02-11     838
2017-02-12     979
2017-02-13     735
2017-02-14     775
2017-02-15     720
2017-02-16     866
2017-02-17     859
2017-02-18     445

[98 rows x 1 columns]

In [108]:
result.to_csv('data/sleeping_normolized.csv')